"use client";

import { Activity, Database, FileCheck2, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";

type Health = { records?: { total?: number; published?: number; unverified?: number; withoutProvenance?: number; stale?: number }; proposals?: Record<string, unknown>[]; documents?: Record<string, unknown>[]; ingestion?: Record<string, unknown>[]; refreshes?: Record<string, unknown>[]; recommendations?: Record<string, unknown>[]; dueSources?: Record<string, unknown>[]; closingDeadlines?: Record<string, unknown>[]; staleIndexes?: Record<string, unknown>[] };
const total = (rows?: Record<string, unknown>[]) => rows?.reduce((sum, row) => sum + Number(row.count ?? 0), 0) ?? 0;
export function DataHealthDashboard() {
  const [health, setHealth] = useState<Health | null>(null); const [message, setMessage] = useState("Loading data health…");
  useEffect(() => { void load(); }, []);
  async function load() { const response = await fetch("/api/v151/data-health", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) return setMessage(body.error ?? "Data health unavailable."); setHealth(body); setMessage(""); }
  async function refresh() { setMessage("Running due official-source checks…"); const response = await fetch("/api/v151/refresh", { method: "POST" }); const body = await response.json().catch(() => ({})); setMessage(response.ok ? `Refresh complete: ${body.results.length} sources checked.` : body.error ?? "Refresh failed."); if (response.ok) await load(); }
  if (!health) return <p className="portal-notice" aria-live="polite">{message}</p>;
  return <><div className="health-grid"><article><Database aria-hidden="true" /><strong>{health.records?.published ?? 0}</strong><span>published records</span></article><article><Activity aria-hidden="true" /><strong>{health.records?.stale ?? 0}</strong><span>stale records</span></article><article><FileCheck2 aria-hidden="true" /><strong>{total(health.documents)}</strong><span>documents tracked</span></article><article><RefreshCw aria-hidden="true" /><strong>{total(health.refreshes)}</strong><span>refresh runs</span></article></div><section className="portal-panel health-detail"><div><span className="eyebrow">Operational evidence</span><h2>Data requiring attention</h2></div><div className="health-summary"><article><strong>{health.records?.unverified ?? 0}</strong><span>missing verification dates</span></article><article><strong>{health.records?.withoutProvenance ?? 0}</strong><span>published without a source</span></article><article><strong>{health.dueSources?.length ?? 0}</strong><span>sources due for review</span></article><article><strong>{health.closingDeadlines?.length ?? 0}</strong><span>deadlines in 30 days</span></article><article><strong>{health.staleIndexes?.length ?? 0}</strong><span>embeddings requiring refresh</span></article><article><strong>{total(health.ingestion)}</strong><span>document-processing jobs</span></article></div><details><summary>Refresh and processing status</summary><dl><div><dt>Content proposals</dt><dd>{health.proposals?.map((row) => `${row.status}: ${row.count}`).join(" · ") || "None"}</dd></div><div><dt>Document jobs</dt><dd>{health.ingestion?.map((row) => `${row.stage}/${row.status}: ${row.count}`).join(" · ") || "None"}</dd></div><div><dt>Refresh runs</dt><dd>{health.refreshes?.map((row) => `${row.status}: ${row.count}`).join(" · ") || "None"}</dd></div><div><dt>Recommendation runs</dt><dd>{health.recommendations?.map((row) => `${row.type}: ${row.runs}`).join(" · ") || "None"}</dd></div></dl></details><button className="button button--primary" type="button" onClick={refresh}><RefreshCw aria-hidden="true" />Run due refreshes</button>{message && <p aria-live="polite">{message}</p>}</section></>;
}
