"use client";

import { Database, FileUp, Network, Save, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";

type Recommendation = { id: string; candidateTitle: string; score: number; label: string; explanations: string[] };
type PublishedCall = { id: string; title: string; summary: string; deadline?: string; disciplines?: string };
const split = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean);

export function StaffPortal() {
  const [state, setState] = useState<"loading" | "ready" | "signed-out" | "unverified" | "unavailable">("loading");
  const [notice, setNotice] = useState("");
  const [calls, setCalls] = useState<PublishedCall[]>([]);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [collaborators, setCollaborators] = useState<Recommendation[]>([]);
  const [submissions, setSubmissions] = useState<{ proposals: { id: string; targetType: string; targetId?: string; status: string; submittedAt: string }[]; documents: { id: string; originalName: string; scanStatus: string; reviewStatus: string }[] }>({ proposals: [], documents: [] });

  const load = useCallback(async () => {
    const sessionResponse = await fetch("/api/v151/session", { cache: "no-store" });
    if (sessionResponse.status === 401) return setState("signed-out");
    if (!sessionResponse.ok) { setNotice((await sessionResponse.json().catch(() => ({}))).error ?? "Database unavailable"); return setState("unavailable"); }
    const session = await sessionResponse.json();
    if (!session.roles.some((role: string) => ["staff", "contributor", "reviewer", "administrator"].includes(role))) return setState("unverified");
    setState("ready");
    const [callResponse, recommendationResponse, collaboratorResponse, submissionResponse] = await Promise.all([fetch("/api/v151/calls", { cache: "no-store" }), fetch("/api/v151/recommendations?type=staff_call", { cache: "no-store" }), fetch("/api/v151/recommendations?type=academic_academic", { cache: "no-store" }), fetch("/api/v151/submissions", { cache: "no-store" })]);
    if (callResponse.ok) setCalls((await callResponse.json()).calls ?? []);
    if (recommendationResponse.ok) setRecommendations((await recommendationResponse.json()).results ?? []);
    if (collaboratorResponse.ok) setCollaborators((await collaboratorResponse.json()).results ?? []);
    if (submissionResponse.ok) setSubmissions(await submissionResponse.json());
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);

  async function submitJson(event: FormEvent<HTMLFormElement>, endpoint: string | ((form: FormData) => string), mapper: (form: FormData) => Record<string, unknown>, success: string) {
    event.preventDefault(); setNotice("Submitting…");
    const formElement = event.currentTarget;
    const form = new FormData(formElement);
    const resolvedEndpoint = typeof endpoint === "function" ? endpoint(form) : endpoint;
    const method = resolvedEndpoint.endsWith("profile") ? "PUT" : /^\/api\/v151\/(calls|modules)\/[^/]+$/.test(resolvedEndpoint) ? "PATCH" : "POST";
    const response = await fetch(resolvedEndpoint, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(mapper(form)) });
    const body = await response.json().catch(() => ({}));
    setNotice(response.ok ? success : body.error ?? "The request could not be completed.");
    if (response.ok) {
      formElement.reset();
      formElement.querySelector<HTMLInputElement>('input[name="existingCallId"],input[name="existingModuleId"]')?.remove();
    }
    if (response.ok && resolvedEndpoint.endsWith("profile")) await load();
  }

  async function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setNotice("Uploading to quarantine…"); const formElement = event.currentTarget;
    const response = await fetch("/api/v151/uploads", { method: "POST", body: new FormData(formElement) });
    const body = await response.json().catch(() => ({})); setNotice(response.ok ? body.message : body.error ?? "Upload failed."); if (response.ok) formElement.reset();
  }

  async function expressInterest(callId: string, title: string) {
    const message = window.prompt(`Explain your interest in “${title}”. This is recorded inside INGENIUM+ and does not send email.`);
    if (!message?.trim()) return;
    const response = await fetch(`/api/v151/calls/${encodeURIComponent(callId)}/interest`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message }) });
    const body = await response.json().catch(() => ({}));
    setNotice(response.ok ? body.message : body.error ?? "Interest could not be recorded.");
  }

  function prepareRevision(targetType: string, targetId?: string) {
    if (!targetId || !["call", "content_record"].includes(targetType)) return;
    const form = document.getElementById(targetType === "call" ? "calls" : "modules") as HTMLFormElement | null;
    if (!form) return;
    const fieldName = targetType === "call" ? "existingCallId" : "existingModuleId";
    let input = form.elements.namedItem(fieldName) as HTMLInputElement | null;
    if (!input) { input = document.createElement("input"); input.type = "hidden"; input.name = fieldName; form.prepend(input); }
    input.value = targetId;
    form.scrollIntoView({ behavior: "smooth", block: "start" });
    setNotice(`Revision mode: complete the ${targetType === "call" ? "call" : "module"} form for ${targetId}. The published version remains live until independent approval.`);
  }

  return <>
    <section className="portal-hero portal-hero--staff"><div><span className="eyebrow">Staff mode · v1.5.1</span><h1>Find collaborators.<br /><span>Make work visible.</span></h1><p>Publish reviewed calls and modules, upload supporting documents and discover academics whose expertise complements the work.</p></div><div className="trust-stack"><span><Database aria-hidden="true" />Versioned institutional data</span><span><ShieldCheck aria-hidden="true" />Role-based review</span><span><Network aria-hidden="true" />Cross-alliance recommendations</span></div></section>
    {state === "loading" && <p className="portal-status">Checking staff access…</p>}
    {state === "signed-out" && <section className="portal-notice"><h2>Sign in to use Staff mode</h2><p>Calls, uploads and collaborator matching require an authenticated and verified staff account.</p><a className="button button--primary" href="/signin-with-chatgpt?return_to=%2Fstaff" target="_top">Sign in with ChatGPT</a></section>}
    {state === "unverified" && <section className="portal-notice portal-notice--warning"><h2>Your account is not yet verified as staff</h2><p>Self-escalation is deliberately disabled. An administrator must grant a staff or contributor membership for your university.</p><Link className="button button--secondary" href="/student">Use Student mode</Link></section>}
    {state === "unavailable" && <section className="portal-notice portal-notice--warning"><h2>Persistent services are awaiting provisioning</h2><p>{notice}</p><p>The checked-in database migration and storage bindings are ready, but this environment has no live D1/R2 resources yet.</p></section>}

    {state === "ready" && <>
      <nav className="staff-subnav" aria-label="Staff workspace sections"><a href="#profile">Profile</a><a href="#calls">Calls</a><a href="#modules">Modules</a><a href="#documents">Documents</a><Link href="/staff/review">Review queue</Link><Link href="/staff/data-health">Data health</Link></nav>
      {notice && <p className="portal-notice portal-notice--compact" aria-live="polite">{notice}</p>}
      <section className="staff-workspace-grid">
        <form id="profile" className="portal-panel portal-form" onSubmit={(event) => submitJson(event, "/api/v151/staff/profile", (form) => ({ homeUniversityId: form.get("homeUniversityId"), title: form.get("academicTitle"), department: form.get("department"), researchInterests: split(form.get("researchInterests")), teachingAreas: split(form.get("teachingAreas")), methods: split(form.get("methods")),
          skillsOffered: split(form.get("skillsOffered")), skillsSought: split(form.get("skillsSought")), methodsOffered: split(form.get("methodsOffered")), methodsSought: split(form.get("methodsSought")),
          facilitiesOffered: split(form.get("facilitiesOffered")), facilitiesSought: split(form.get("facilitiesSought")), teachingOffered: split(form.get("teachingOffered")),
          teachingSought: split(form.get("teachingSought")), collaborationFormats: split(form.get("collaborationFormats")), collaborationGoals: split(form.get("collaborationGoals")),
          languages: split(form.get("languages")), availability: form.get("availability"), contactRoute: form.get("contactRoute"), discoverable: form.get("discoverable") === "on" }), "Staff profile saved.")}>
          <span className="eyebrow">Academic profile</span><h2>Tell the network what you can contribute</h2><div className="form-grid"><label><span>Home university ID</span><input name="homeUniversityId" placeholder="university-mtu" required /></label><label><span>Academic title</span><input name="academicTitle" placeholder="Lecturer" /></label><label className="form-grid__wide"><span>Department</span><input name="department" /></label><label className="form-grid__wide"><span>Research interests</span><input name="researchInterests" placeholder="AI ethics, digital education" /></label><label><span>Teaching areas</span><input name="teachingAreas" /></label><label><span>General methods</span><input name="methods" placeholder="mixed methods, prototyping" /></label><label><span>Skills offered</span><input name="skillsOffered" placeholder="data modelling, co-design" /></label><label><span>Skills sought</span><input name="skillsSought" placeholder="policy evaluation, GIS" /></label><label><span>Methods offered</span><input name="methodsOffered" /></label><label><span>Methods sought</span><input name="methodsSought" /></label><label><span>Facilities offered</span><input name="facilitiesOffered" /></label><label><span>Facilities sought</span><input name="facilitiesSought" /></label><label><span>Teaching topics offered</span><input name="teachingOffered" /></label><label><span>Teaching partnership sought</span><input name="teachingSought" /></label><label><span>Collaboration formats</span><input name="collaborationFormats" placeholder="hybrid module, research consortium" /></label><label><span>Preferred contact route</span><input name="contactRoute" placeholder="Request introduction in INGENIUM+" /></label><label className="form-grid__wide"><span>Collaboration goals</span><input name="collaborationGoals" placeholder="Horizon Europe, joint module" /></label><label><span>Languages</span><input name="languages" placeholder="English, French" /></label><label><span>Availability</span><input name="availability" placeholder="2 hours/week" /></label></div><label className="consent-row"><input type="checkbox" name="discoverable" /><span>Opt in to being recommended to other verified academics.</span></label><button className="button button--primary" type="submit"><Save aria-hidden="true" />Save staff profile</button>
        </form>
        <aside className="portal-panel recommendation-explainer"><span className="eyebrow">Your call matches</span><h2><Sparkles aria-hidden="true" />Recommended collaborations</h2>{recommendations.length ? <div className="compact-matches">{recommendations.slice(0, 5).map((item) => <article key={item.id}><strong>{item.candidateTitle}</strong><span>{item.score} · {item.label}</span><p>{item.explanations[0]}</p></article>)}</div> : <p>Save your profile to generate explainable matches against published calls.</p>}</aside>
        <aside className="portal-panel recommendation-explainer"><span className="eyebrow">Opt-in academic discovery</span><h2><Network aria-hidden="true" />Recommended collaborators</h2>{collaborators.length ? <div className="compact-matches">{collaborators.slice(0, 5).map((item) => <article key={item.id}><strong>{item.candidateTitle}</strong><span>{item.score} · {item.label}</span><p>{item.explanations[0]}</p></article>)}</div> : <p>Only opted-in verified academics can appear. Save your profile to calculate complementary matches.</p>}</aside>

        <form id="calls" className="portal-panel portal-form" onSubmit={(event) => submitJson(event, (form) => form.get("existingCallId") ? `/api/v151/calls/${encodeURIComponent(String(form.get("existingCallId")))}` : "/api/v151/calls", (form) => ({ title: form.get("title"), summary: form.get("summary"), description: form.get("description"), callType: form.get("callType"), organizationId: form.get("organizationId"), disciplines: split(form.get("disciplines")), methods: split(form.get("methods")),
          skillsOffered: split(form.get("skillsOffered")), skillsSought: split(form.get("skillsSought")), methodsOffered: split(form.get("methodsOffered")), methodsSought: split(form.get("methodsSought")), facilitiesOffered: split(form.get("facilitiesOffered")), facilitiesSought: split(form.get("facilitiesSought")),
          needs: split(form.get("needs")), teachingThemes: split(form.get("teachingThemes")), targetPartnerTypes: split(form.get("targetPartnerTypes")), eligibility: split(form.get("eligibility")), languages: split(form.get("languages")), countries: split(form.get("countries")), deliveryMode: form.get("deliveryMode"), expectedContribution: form.get("expectedContribution"), projectStage: form.get("projectStage"), fundingStatus: form.get("fundingStatus"), fundingProgramme: form.get("fundingProgramme"), timeCommitment: form.get("timeCommitment"), startDate: form.get("startDate"), endDate: form.get("endDate"), deadline: form.get("deadline"), collaborationFormat: form.get("collaborationFormat"), location: form.get("location"), confidentialityLevel: form.get("confidentialityLevel"), contactWorkflow: form.get("contactWorkflow"), targetPartnerCount: form.get("targetPartnerCount") ? Number(form.get("targetPartnerCount")) : undefined, sourceUrl: form.get("sourceUrl") }), "Call submitted to the review queue.")}>
          <span className="eyebrow">Collaboration call</span><h2>Invite the right expertise</h2><label><span>Title</span><input name="title" required /></label><label><span>Short summary</span><textarea name="summary" required rows={2} /></label><label><span>Full description</span><textarea name="description" required rows={5} /></label><div className="form-grid"><label><span>Call type</span><input name="callType" placeholder="research / teaching / project" /></label><label><span>University ID</span><input name="organizationId" /></label><label><span>Disciplines</span><input name="disciplines" /></label><label><span>General methods</span><input name="methods" /></label><label><span>Skills offered</span><input name="skillsOffered" /></label><label><span>Skills sought</span><input name="skillsSought" /></label><label><span>Methods offered</span><input name="methodsOffered" /></label><label><span>Methods sought</span><input name="methodsSought" /></label><label><span>Facilities offered</span><input name="facilitiesOffered" /></label><label><span>Facilities sought</span><input name="facilitiesSought" /></label><label><span>Other expertise needed</span><input name="needs" /></label><label><span>Teaching themes</span><input name="teachingThemes" /></label><label><span>Target partner types</span><input name="targetPartnerTypes" /></label><label><span>Eligibility</span><input name="eligibility" /></label><label><span>Languages</span><input name="languages" /></label><label><span>Countries</span><input name="countries" /></label><label><span>Delivery mode</span><input name="deliveryMode" /></label><label><span>Collaboration format</span><input name="collaborationFormat" /></label><label><span>Expected contribution</span><input name="expectedContribution" /></label><label><span>Project stage</span><input name="projectStage" /></label><label><span>Funding status</span><input name="fundingStatus" /></label><label><span>Funding programme</span><input name="fundingProgramme" /></label><label><span>Time commitment</span><input name="timeCommitment" /></label><label><span>Location</span><input name="location" /></label><label><span>Start date</span><input name="startDate" type="date" /></label><label><span>End date</span><input name="endDate" type="date" /></label><label><span>Response deadline</span><input name="deadline" type="date" /></label><label><span>Target partners</span><input name="targetPartnerCount" type="number" min="1" max="100" /></label><label><span>Confidentiality</span><input name="confidentialityLevel" placeholder="public / alliance / restricted" /></label><label><span>Contact workflow</span><input name="contactWorkflow" placeholder="Express interest in INGENIUM+" /></label><label className="form-grid__wide"><span>Official source URL</span><input name="sourceUrl" type="url" /></label></div><button className="button button--primary" type="submit"><Network aria-hidden="true" />Submit for review</button>
        </form>

        <form id="modules" className="portal-panel portal-form" onSubmit={(event) => submitJson(event, (form) => form.get("existingModuleId") ? `/api/v151/modules/${encodeURIComponent(String(form.get("existingModuleId")))}` : "/api/v151/modules", (form) => ({ title: form.get("title"), summary: form.get("summary"), fullDescription: form.get("fullDescription"), organizationId: form.get("organizationId"), themes: split(form.get("themes")), methods: split(form.get("methods")), languages: split(form.get("languages")), studyLevels: split(form.get("studyLevels")), prerequisites: split(form.get("prerequisites")), learningOutcomes: split(form.get("learningOutcomes")), skillsDeveloped: split(form.get("skillsDeveloped")), eligibility: form.get("eligibility"), deliveryMode: form.get("deliveryMode"), campus: form.get("campus"), location: form.get("location"), semester: form.get("semester"), startDate: form.get("startDate"), endDate: form.get("endDate"), applicationDeadline: form.get("applicationDeadline"), workload: form.get("workload"), recognitionInformation: form.get("recognitionInformation"), capacity: form.get("capacity") ? Number(form.get("capacity")) : undefined, ects: form.get("ects") ? Number(form.get("ects")) : undefined, officialUrl: form.get("officialUrl") }), "Module submitted to the review queue.")}>
          <span className="eyebrow">Learning opportunity</span><h2>Publish a module to students</h2><label><span>Module title</span><input name="title" required /></label><label><span>Student summary</span><textarea name="summary" required rows={2} /></label><label><span>Full description</span><textarea name="fullDescription" required rows={4} /></label><div className="form-grid"><label><span>University ID</span><input name="organizationId" /></label><label><span>ECTS</span><input name="ects" type="number" min="0" max="60" step="0.5" /></label><label><span>Themes</span><input name="themes" /></label><label><span>Methods</span><input name="methods" /></label><label><span>Languages</span><input name="languages" /></label><label><span>Study levels</span><input name="studyLevels" /></label><label><span>Prerequisites</span><input name="prerequisites" /></label><label><span>Learning outcomes</span><input name="learningOutcomes" /></label><label><span>Skills developed</span><input name="skillsDeveloped" /></label><label><span>Delivery mode</span><input name="deliveryMode" /></label><label><span>Campus</span><input name="campus" /></label><label><span>Location</span><input name="location" /></label><label><span>Semester</span><input name="semester" /></label><label><span>Start date</span><input name="startDate" type="date" /></label><label><span>End date</span><input name="endDate" type="date" /></label><label><span>Application deadline</span><input name="applicationDeadline" type="date" /></label><label><span>Workload</span><input name="workload" /></label><label><span>Capacity</span><input name="capacity" type="number" min="0" /></label><label className="form-grid__wide"><span>Eligibility</span><input name="eligibility" /></label><label className="form-grid__wide"><span>Recognition information</span><textarea name="recognitionInformation" rows={2} /></label><label className="form-grid__wide"><span>Official application URL</span><input name="officialUrl" type="url" /></label></div><button className="button button--primary" type="submit">Submit module for review</button>
        </form>

        <form id="documents" className="portal-panel portal-form upload-panel" onSubmit={upload}><span className="eyebrow">Secure evidence</span><h2><FileUp aria-hidden="true" />Upload a supporting document</h2><p>PDF, Office documents, CSV, PNG and JPEG up to 20 MB. Files remain private and quarantined until both malware scanning and human review succeed.</p><label><span>Document</span><input name="file" type="file" required accept=".pdf,.docx,.xlsx,.pptx,.csv,.png,.jpg,.jpeg" /></label><label><span>University ID</span><input name="organizationId" /></label><label><span>Related call ID <small>optional</small></span><input name="callId" /></label><label><span>Related module/record ID <small>optional</small></span><input name="recordId" /></label><button className="button button--dark" type="submit">Upload to quarantine</button></form>
        <section className="portal-panel"><span className="eyebrow">My submissions</span><h2>Status and processing</h2><div className="compact-matches">{submissions.proposals.map((item) => <article key={item.id}><strong>{item.targetType.replaceAll("_", " ")}</strong><span>{item.status}</span><p>Submitted {new Date(item.submittedAt).toLocaleDateString()}</p>{item.targetId && ["call", "content_record"].includes(item.targetType) && <button type="button" onClick={() => prepareRevision(item.targetType, item.targetId)}>Prepare revision</button>}</article>)}{submissions.documents.map((item) => <article key={item.id}><strong>{item.originalName}</strong><span>Scan {item.scanStatus} · review {item.reviewStatus}</span></article>)}</div>{!submissions.proposals.length && !submissions.documents.length && <p>No submissions yet.</p>}</section>
      </section>

      <section className="portal-recommendations"><div className="section-heading"><div><span className="eyebrow">Published calls</span><h2>Open collaboration across the alliance</h2></div></div>{calls.length ? <div className="match-grid">{calls.map((call) => <article key={call.id}><h3>{call.title}</h3><p>{call.summary}</p>{call.deadline && <small>Deadline {call.deadline}</small>}<button type="button" className="button button--secondary" onClick={() => expressInterest(call.id, call.title)}>Express interest</button></article>)}</div> : <div className="empty-state"><h2>No reviewed calls are published yet</h2><p>The first approved call will appear here and enter the matching engine immediately.</p></div>}</section>
    </>}
  </>;
}
