import type { Entity, Relationship, Source } from "./data";

export const CATALOGUE_ENRICHMENT_DATE = "2026-10-01";

export const catalogueEnrichmentSources: Source[] = [
  {
    id: "fc-cat-a-taste-of-german-culture-and-language",
    title: "A Taste of German Culture and Language.",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/a-taste-of-german-culture-and-language/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-a-taste-of-romanian-language-and-culture",
    title: "A Taste of Romanian Language and Culture",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/a-taste-of-romanian-language-and-culture/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-a-taste-of-italian-culture-and-language",
    title: "A Taste of Italian Culture and Language.",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/a-taste-of-italian-culture-and-language/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-a-taste-of-finnish-culture-and-language",
    title: "A Taste of Finnish Culture and Language",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/a-taste-of-finnish-culture-and-language/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-a-taste-of-spanish-culture-language",
    title: "A Taste of Spanish Culture & Language",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/a-taste-of-spanish-culture-language/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-a-taste-of-french-culture-and-language",
    title: "A Taste of French Culture and Language",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/a-taste-of-french-culture-and-language/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-taste-of-greek-language-and-culture",
    title: "Α taste of Greek Language and Culture",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/%ce%b1-taste-of-greek-culture-and-language/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
  {
    id: "fc-cat-course-catalogue-contributions-2026",
    title: "Proposals for Course Catalogue Contributions",
    kind: "Official INGENIUM Annual Education Call page",
    url: "https://ingenium-university.eu/iec-faculty/ingenium-annual-education-call-2026-2027/course-catalogue-contributions-2/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_ENRICHMENT_DATE,
  },
];

export const catalogueEnrichmentEntities: Entity[] = [
  {
    id: "course-taste-german-culture-and-language",
    slug: "a-taste-of-german-culture-and-language",
    title: "A Taste of German Culture and Language.",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "This course introduces you to basic German for everyday life at university. You will learn how to introduce yourself, ask simple questions, talk about places on campus, numbers, food, and everyday situations. Through short activities, dialogues, and exercises, you will build c...",
    fullDescription: "This course introduces you to basic German for everyday life at university. You will learn how to introduce yourself, ask simple questions, talk about places on campus, numbers, food, and everyday situations. Through short activities, dialogues, and exercises, you will build confidence in using German in real-life contexts.",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-hka"],
    hostUniversityId: "university-hka",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "INGENIUM students and staff; check the detail page for any prerequisites",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-german-culture-and-language/",
    sourceId: "fc-cat-a-taste-of-german-culture-and-language",
    sourceIds: ["fc-cat-a-taste-of-german-culture-and-language", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "course-taste-romanian-language-and-culture",
    slug: "a-taste-of-romanian-language-and-culture",
    title: "A Taste of Romanian Language and Culture",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "This moduleisdesigned forstudents and staffwhoarecuriousabouttheRomanianlanguage–whetheryouare preparingforamobilityprogrammeat“GheorgheAsachi”TechnicalUniversityofIașiorsimply wanttostart learningRomanianonyourown.ThecourseisanintroductiontoRomanianasaforeignlanguage,organise...",
    fullDescription: "This moduleisdesigned forstudents and staffwhoarecuriousabouttheRomanianlanguage–whetheryouare preparingforamobilityprogrammeat“GheorgheAsachi”TechnicalUniversityofIașiorsimply wanttostart learningRomanianonyourown.ThecourseisanintroductiontoRomanianasaforeignlanguage,organisedin 8unitscoveringelements from A0toA2levelswithelements of the B1 level. Each unitisstructured to takearound 1hour– 1 hour anda halfof study and includes: ·A video lesson to guideyoustep bystep– between 30and 40minutes ·AV ocabulary sheetto help you learn thekey words and expressions youwillfindit helpful to have this documenthandy when starting thepracticalactivities ·A Worksheet topracticeand applyboth vocabularyandgrammar(audioexercises arealsoincluded), with ·An A nswer Key ·A Self-assessmentquiz availableviaGoogleForm, withalinkand QRcodeincludedineach “UNITContents” section –your resultscome...",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-tuiasi"],
    hostUniversityId: "university-tuiasi",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "INGENIUM students and staff; check the detail page for any prerequisites",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-romanian-language-and-culture/",
    sourceId: "fc-cat-a-taste-of-romanian-language-and-culture",
    sourceIds: ["fc-cat-a-taste-of-romanian-language-and-culture", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "course-taste-italian-culture-and-language",
    slug: "a-taste-of-italian-culture-and-language",
    title: "A Taste of Italian Culture and Language.",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "!image.pngBenvenut o al corso di pre-mobilità per la lingua italiana. -o =maschile !image%20%281%29.pngBenvenut a al corso di pre-mobilità per la lingua italiana. -a =femminile This is an online Italian course for beginners, designed for international and Erasmus students comi...",
    fullDescription: "!image.pngBenvenut o al corso di pre-mobilità per la lingua italiana. -o =maschile !image%20%281%29.pngBenvenut a al corso di pre-mobilità per la lingua italiana. -a =femminile This is an online Italian course for beginners, designed for international and Erasmus students coming to study in Italy. The course is divided into 10 short, clear lessons. In each lesson, you will learn to communicate in real-life situations, useful for everyday and university life in Italy. During the course, you will learn to: Introduce yourself Greeting and speaking to people Understand and use important words Pronounce Italian well Learn about Italian culture and society The course is online and asynchronous: You can study whenever you want and at your own pace. Happy studying and... welcome to Italy! \\\\\\\\\\\\ Questo è un corso online di italiano per principianti, pensato per studenti internazionali ed...",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-uda"],
    hostUniversityId: "university-uda",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "INGENIUM students and staff; check the detail page for any prerequisites",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-italian-culture-and-language/",
    sourceId: "fc-cat-a-taste-of-italian-culture-and-language",
    sourceIds: ["fc-cat-a-taste-of-italian-culture-and-language", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "course-taste-finnish-culture-and-language",
    slug: "a-taste-of-finnish-culture-and-language",
    title: "A Taste of Finnish Culture and Language",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "A TASTE OF FINNISH CULTURE AND LANGUAGE COURSE This is a premobility course offered by the INGENIUM European University alliance and South-Eastern Finland University of Applied Sciences (Xamk). If you are coming to Finland and Xamk for the staff or student mobility, this cours...",
    fullDescription: "A TASTE OF FINNISH CULTURE AND LANGUAGE COURSE This is a premobility course offered by the INGENIUM European University alliance and South-Eastern Finland University of Applied Sciences (Xamk). If you are coming to Finland and Xamk for the staff or student mobility, this course will provide you with useful information about Finnish society, everyday life, and the Finnish language. You can progress through the course according to your interests: either in order or by choosing the units and activities that interest you the most. Once you have opened all the assignments or marked them as completed, you can download a certificate in the unit 10.",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-xamk"],
    hostUniversityId: "university-xamk",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "Open for all (Bachelor, Master, Postgraduate, PhD students and staff members)",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-finnish-culture-and-language/",
    sourceId: "fc-cat-a-taste-of-finnish-culture-and-language",
    sourceIds: ["fc-cat-a-taste-of-finnish-culture-and-language", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "course-taste-spanish-culture-language",
    slug: "a-taste-of-spanish-culture-language",
    title: "A Taste of Spanish Culture & Language",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "This Spanish course is designed for students who have already completed level A1, as the content covers levels A2–B1. It features numerous activities for practicing various Spanish verb tenses while also introducing cultural topics related to Spain and the region where our uni...",
    fullDescription: "This Spanish course is designed for students who have already completed level A1, as the content covers levels A2–B1. It features numerous activities for practicing various Spanish verb tenses while also introducing cultural topics related to Spain and the region where our university is located: Asturias.",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-uniovi"],
    hostUniversityId: "university-uniovi",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "INGENIUM students and staff; check the detail page for any prerequisites",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-spanish-culture-language/",
    sourceId: "fc-cat-a-taste-of-spanish-culture-language",
    sourceIds: ["fc-cat-a-taste-of-spanish-culture-language", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "course-taste-french-culture-and-language",
    slug: "a-taste-of-french-culture-and-language",
    title: "A Taste of French Culture and Language",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "Welcome to our online course organised by our URN language team and open to all INGENIUM staff and students. This course is aimed for beginners (A1/A2) and comprises 5 modules of 30 minutes each, providing simple dialogues and helpful ideas for getting going in French. This co...",
    fullDescription: "Welcome to our online course organised by our URN language team and open to all INGENIUM staff and students. This course is aimed for beginners (A1/A2) and comprises 5 modules of 30 minutes each, providing simple dialogues and helpful ideas for getting going in French. This course also gives you some tips on understanding French culture.",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-urn"],
    hostUniversityId: "university-urn",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "INGENIUM students and staff; check the detail page for any prerequisites",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-french-culture-and-language/",
    sourceId: "fc-cat-a-taste-of-french-culture-and-language",
    sourceIds: ["fc-cat-a-taste-of-french-culture-and-language", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "course-taste-greek-language-and-culture",
    slug: "taste-of-greek-language-and-culture",
    title: "Α taste of Greek Language and Culture",
    type: "course",
    subtype: "Language and culture course",
    studentSummary: "The course aims at familiarizing incoming students and staff with the Greek language and culture, providing extra information about the region of Crete. It comprises ten thematic Units, two reviewing units, audio and video material, plus the links to two grammar e-companions. ...",
    fullDescription: "The course aims at familiarizing incoming students and staff with the Greek language and culture, providing extra information about the region of Crete. It comprises ten thematic Units, two reviewing units, audio and video material, plus the links to two grammar e-companions. Each unit conists of three components: a) The language component (signalled with red), which focuses on everyday spoken Greek (levels A1-A2). It is based on short texts (with their explanation and most important words or phrases). Each text serves as the basis for particular remarks about vocabulary/communication and grammar/structure. The text sub-modules are completed with basic exercises to practise on the phenomena under examination. At the end of each Unit you can find a key to the exercises. b) The cultural component (signalled with green), which focuses on attitudes, beliefs and practices of the...",
    status: "Access unverified",
    availability: "Public catalogue page; no current dates or enrolment window are stated",
    universityIds: ["university-uoc"],
    hostUniversityId: "university-uoc",
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Virtual",
    ects: 0,
    eligibility: "None",
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/%ce%b1-taste-of-greek-culture-and-language/",
    sourceId: "fc-cat-taste-of-greek-language-and-culture",
    sourceIds: ["fc-cat-taste-of-greek-language-and-culture", "course-catalogue-2026", "fc-full-taste-courses"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
  },
  {
    id: "opportunity-course-catalogue-contributions-2026",
    slug: "course-catalogue-contributions-2026-2027",
    title: "Course Catalogue Contributions 2026/2027",
    type: "opportunity",
    subtype: "Annual Education Call proposal route",
    studentSummary: "Academic staff can open existing accredited online or blended courses to students across the alliance through the shared catalogue.",
    fullDescription: "This Annual Education Call route accepts existing accredited courses that students from other INGENIUM universities can follow virtually or in blended mode. The fast-track deadline is 16 October 2026 for semester 2 of 2026/27; the general deadline is 18 December 2026 for 2027/28.",
    status: "Open now",
    availability: "Open on 1 October 2026; deadlines 16 October and 18 December 2026",
    universityIds: ["university-mtu","university-hka","university-xamk","university-hs","university-uoc","university-mus","university-uniovi","university-urn","university-uda","university-tuiasi"],
    themes: ["Course sharing", "Collaborative education", "European campus"],
    applicationOpenDate: "2026-09-14",
    applicationDeadline: "2026-12-18",
    deliveryMode: "Fully online, blended, or online with an optional on-site component",
    eligibility: "Academic staff offering an accredited course with places available to students from partner universities",
    actionLabel: "Open the proposal route",
    officialUrl: "https://ingenium-university.eu/iec-faculty/ingenium-annual-education-call-2026-2027/course-catalogue-contributions-2/",
    sourceId: "fc-cat-course-catalogue-contributions-2026",
    sourceIds: ["fc-cat-course-catalogue-contributions-2026", "fc29-annual-education-call"],
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
    dataClassification: "verified",
    featured: true,
  },
];

export const catalogueEnrichmentOverrides: Partial<Record<string, Partial<Entity>>> = {
  "microcredential-from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-ba": {
    ects: 4,
    capacity: "10",
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-based-education/",
    fullDescription: "this INGENIUM micro-credential that provides advanced training in green chemistry and sustainable chemical processes, focusing on the valorization of waste streams (e.g., CO₂, lignin, glycerol) through catalytic and materials-based approaches. Building on the research outcomes of the INGENIUM project UP2Green, the course integrates chemistry, materials science, and environmental process engineering into a research-based learning experience. Participants will develop knowledge on the design and application of metal nanoparticle catalysts, CO₂ capture and reuse, and sustainable process integration. The course combines asynchronous modules with joint interdisciplinary sessions, enabling learners to apply scientific concepts to real case studies. It prepares doctoral students and early-career professionals to address challenges in the green and circular economy, enhancing both research and professional competences.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "module-acute-care-research-development": {
    officialUrl: "https://ingenium-university.eu/courses/research-and-development-in-acute-care-nursing-2/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-evidence-based-practice-and-implementation-in-acute-care-nursing": {
    officialUrl: "https://ingenium-university.eu/courses/evidence-based-practice-and-implementation-in-acute-care-nursing-2/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "module-acute-care-professional-development": {
    officialUrl: "https://ingenium-university.eu/courses/advanced-practice-nursing-and-professional-development-in-acute-care-nursing-2/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-innovation-management-entrepreneurship": {
    ects: 0,
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/innovation-management-and-entrepreneurship/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "learning-swedish-culture-language": {
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/a-taste-of-swedish-culture-and-language/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "microcredential-climate-infrastructure": {
    ects: 2,
    capacity: "30",
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/climate-adapted-urban-infrastructure/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-sustainable-wellbeing": {
    ects: 5,
    capacity: "10",
    deliveryMode: "Online",
    officialUrl: "https://ingenium-university.eu/courses/sustainable-wellbeing-in-changing-society/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-ecec-finland": {
    ects: 3,
    deliveryMode: "Self-learning",
    officialUrl: "https://ingenium-university.eu/courses/early-childhood-education-and-care-ecec-in-finland/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-beginners-finnish-2": {
    ects: 3,
    capacity: "50",
    deliveryMode: "Self-learning",
    officialUrl: "https://ingenium-university.eu/courses/beginners-finnish-2/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-beginners-finnish-1": {
    ects: 2,
    capacity: "50",
    deliveryMode: "Self-learning",
    officialUrl: "https://ingenium-university.eu/courses/beginners-finnish-1/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-culture-finland": {
    ects: 3,
    capacity: "50",
    deliveryMode: "Self-learning",
    officialUrl: "https://ingenium-university.eu/courses/culture-finland/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-using-wellbeing-skills-to-promote-studying-ability": {
    ects: 2,
    capacity: "20",
    deliveryMode: "Self-learning",
    officialUrl: "https://ingenium-university.eu/courses/using-wellbeing-skills-to-promote-studying-ability/",
    fullDescription: "The aim of this course is to promote students' study ability and wellbeing. The course offers tools to support learning, coping and wellbeing. In this course, students study strongly themselves, reflecting on their own learning and well-being. The course contains learning material in many different formats (e.g. texts, videos, podcasts). This course is completed independently online on Xamk Learn digital learning environment. The participant acquires Xamk user credentials before the course begins by identifying electronically with a passport or a biometric EU/EEA identity card, using Candour ID mobile application.Once the enrolment period has ended, you will receive Candour ID instructions by email (from ). Enrollment for this course is open till 27.09.2026.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-health-promotion-strategies-for-health-professionals": {
    ects: 2,
    capacity: "20",
    deliveryMode: "Physical",
    officialUrl: "https://ingenium-university.eu/courses/health-promotion-strategies-for-health-professionals-2/",
    fullDescription: "An on-site intensive course for health-science professionals on the design and planning of health-promotion strategies. - Health promotion: concept and evolution - Social determinants of health - Modifiable risk factors - Behavioural theories (Health Belief Model, I-Change Model, Transtheoretical Model of Health Behaviour, Behaviour Change Wheel) This microcredential has a €30 fee for certification purposes.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "microcredential-micro-credential-learning-design": {
    ects: 1,
    capacity: "50",
    deliveryMode: "Online",
    officialUrl: "https://ingenium-university.eu/courses/micro-credential-learning-design/",
    fullDescription: "A self-paced, self-study course on the basics of micro-credential learning design. - Key pedagogical models and universal design for learning - Basics of student-centred learning design - Assessment design - Flexible learning materials - Accessibility",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "microcredential-towards-framework-2026": {
    ects: 1,
    capacity: "50",
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/towards-ingenium-micro-credentials-framework/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-education-for-sustainable-development-esd-for-university-staff": {
    officialUrl: "https://ingenium-university.eu/courses/education-for-sustainable-development-esd-for-university-staff/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-digital-accessibility": {
    officialUrl: "https://ingenium-university.eu/courses/digital-accessibility/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-gender-scape-a-serious-game-about-gender-equality": {
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/gender-scape-a-serious-game-about-gender-equality/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-rethinking-assessment": {
    ects: 8,
    officialUrl: "https://ingenium-university.eu/courses/rethinking-assessment-in-higher-education-inclusive-feedback-rich-and-ai-supported-practices/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-science-meets-industry-driving-innovation-through-industry-challenges": {
    officialUrl: "https://ingenium-university.eu/courses/science-meets-industry-driving-innovation-through-industry-challenges/",
    fullDescription: "This BIP brings together academia and industry by tasking interdisciplinary MSc and PhD student groups with addressing concrete challenges provided by industrial partners, from different domains, e.g., smart cities and mobility, digitalization and AI, etc, that can drive innovation forward.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-science-meets-industry-ethical-ai-development": {
    officialUrl: "https://ingenium-university.eu/courses/science-meets-industry-ethical-ai-development/",
    fullDescription: "Artificial Intelligence (AI) is transforming industries and research fields across Europe and globally. Ensuring the ethical development and deployment of AI systems is critical to safeguard human rights, fairness, and societal well-being. This program addresses a pressing need for interdisciplinary education on AI ethics, tailored to the diverse academic backgrounds of the INGENIUM Alliance students.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-science-meets-industry-creative-convergence-innovating-industries-togeth": {
    officialUrl: "https://ingenium-university.eu/courses/science-meets-industry-creative-convergence-innovating-industries-together/",
    fullDescription: "By forging connections between diverse fields, this initiative exemplifies the synergy that arises when creativity meets collaboration. Students will engage in a dynamic process of innovation, journeying through three pivotal pillars of the 5Cos framework: co-ideation, co-valuation, and co-design (co-test, and co-launch). These phases of the innovation process will empower participants to co-create visionary packaging solutions that are not only functional and sustainable but also tailored to the challenges posed by unconventional product shapes. The event seeks to bridge academia and industry, providing a platform where emerging talents can confront real-world challenges and propose transformative solutions.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-intercultural-team-based-learning": {
    officialUrl: "https://ingenium-university.eu/courses/intercultural-team-based-learning/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by": {
    officialUrl: "https://ingenium-university.eu/courses/crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by-commercial-and-cardanol-derivatives/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-coil-collaboration-to-promote-technical-language-and-intercultural-compe": {
    officialUrl: "https://ingenium-university.eu/courses/coil-collaboration-to-promote-technical-language-and-intercultural-competence-technical-english-c1-english-across-the-disciplines/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-international-communication": {
    officialUrl: "https://ingenium-university.eu/courses/international-communication/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "initiative-bmc": {
    ects: 0,
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/business-model-canvas/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-how-to-become-a-disability-ambassador": {
    officialUrl: "https://ingenium-university.eu/courses/how-to-become-a-disability-ambassador/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-introduction-to-polymer-characterization": {
    officialUrl: "https://ingenium-university.eu/courses/introduction-to-polymer-characterization/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "initiative-staff-academy": {
    ects: 0,
    deliveryMode: "All",
    officialUrl: "https://ingenium-university.eu/courses/staff-academy/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "course-differential-holistic-and-integrative-approach-to-patient-care": {
    officialUrl: "https://ingenium-university.eu/courses/differential-holistic-and-integrative-approach-to-patient-care/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "learning_resource-sustainability-course-materials-for-teaching": {
    deliveryMode: "Virtual",
    officialUrl: "https://ingenium-university.eu/courses/sustainability-course-material-for-teaching/",
    fullDescription: "These are flexible to use course materials, so this is no course. No registration needed - This material is for teaching, so use enrollment to access the material. The target-group is teachers who will integrate these materials in their programs and courses for students. The materials can also be broadly used for competence development for staff. The materials can be shared under the creative commons licence CC-BY-NC-SA 4.0.",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
  },
  "bip-academic-communication": {
    status: "Upcoming",
    availability: "Online from 5 October to 25 November 2026; intensive week in Karlsruhe from 30 November to 4 December 2026",
    startDate: "2026-10-05",
    endDate: "2026-12-04",
    dateLabel: "Online 5 October–25 November; Karlsruhe 30 November–4 December 2026",
    ects: 5,
    workload: "140 hours total, including about 50 hours online",
    deliveryMode: "Blended",
    mobilityType: "Online preparation plus an intensive on-site week in Karlsruhe",
    universityIds: ["university-hka","university-xamk","university-mtu","university-tuiasi"],
    hostUniversityId: "university-hka",
    eligibility: "Students apply through their home institution; the programme is interdisciplinary",
    officialUrl: "https://ingenium-university.eu/event/bip-academic-communication/",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
  },
  "opportunity-ingenium-ambassadors-2026": {
    status: "Open now",
    availability: "Applications opened 1 October and close 18 October 2026 at 23:59 CET",
    applicationOpenDate: "2026-10-01",
    applicationDeadline: "2026-10-18",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
  },
  "opportunity-annual-education-call-2026": {
    status: "Open now",
    availability: "Open on 1 October 2026: fast-track deadline 16 October; general expression of interest 13 November; final deadline 18 December 2026",
    startDate: "2026-09-14",
    endDate: "2027-07-31",
    applicationOpenDate: "2026-09-14",
    applicationDeadline: "2026-12-18",
    lastVerified: CATALOGUE_ENRICHMENT_DATE,
    confidence: "High",
  },
};

export const catalogueEnrichmentRelationships: Relationship[] = [
  { id: "rel-cat-a-taste-of-german-culture-and-language-family", source: "course-taste-german-culture-and-language", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "A Taste of German Culture and Language. is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-a-taste-of-german-culture-and-language", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-german-culture-and-language-host", source: "course-taste-german-culture-and-language", target: "university-hka", type: "hosted_by", label: "Hosted by", explanation: "A Taste of German Culture and Language. is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-a-taste-of-german-culture-and-language"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-romanian-language-and-culture-family", source: "course-taste-romanian-language-and-culture", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "A Taste of Romanian Language and Culture is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-a-taste-of-romanian-language-and-culture", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-romanian-language-and-culture-host", source: "course-taste-romanian-language-and-culture", target: "university-tuiasi", type: "hosted_by", label: "Hosted by", explanation: "A Taste of Romanian Language and Culture is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-a-taste-of-romanian-language-and-culture"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-italian-culture-and-language-family", source: "course-taste-italian-culture-and-language", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "A Taste of Italian Culture and Language. is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-a-taste-of-italian-culture-and-language", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-italian-culture-and-language-host", source: "course-taste-italian-culture-and-language", target: "university-uda", type: "hosted_by", label: "Hosted by", explanation: "A Taste of Italian Culture and Language. is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-a-taste-of-italian-culture-and-language"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-finnish-culture-and-language-family", source: "course-taste-finnish-culture-and-language", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "A Taste of Finnish Culture and Language is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-a-taste-of-finnish-culture-and-language", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-finnish-culture-and-language-host", source: "course-taste-finnish-culture-and-language", target: "university-xamk", type: "hosted_by", label: "Hosted by", explanation: "A Taste of Finnish Culture and Language is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-a-taste-of-finnish-culture-and-language"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-spanish-culture-language-family", source: "course-taste-spanish-culture-language", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "A Taste of Spanish Culture & Language is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-a-taste-of-spanish-culture-language", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-spanish-culture-language-host", source: "course-taste-spanish-culture-language", target: "university-uniovi", type: "hosted_by", label: "Hosted by", explanation: "A Taste of Spanish Culture & Language is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-a-taste-of-spanish-culture-language"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-french-culture-and-language-family", source: "course-taste-french-culture-and-language", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "A Taste of French Culture and Language is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-a-taste-of-french-culture-and-language", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-a-taste-of-french-culture-and-language-host", source: "course-taste-french-culture-and-language", target: "university-urn", type: "hosted_by", label: "Hosted by", explanation: "A Taste of French Culture and Language is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-a-taste-of-french-culture-and-language"], dataClassification: "verified" },
  { id: "rel-cat-taste-of-greek-language-and-culture-family", source: "course-taste-greek-language-and-culture", target: "learning-resource-taste-cultures-languages", type: "part_of", label: "Part of course family", explanation: "Α taste of Greek Language and Culture is one of the individual A Taste of INGENIUM language and culture catalogue entries.", sourceIds: ["fc-cat-taste-of-greek-language-and-culture", "fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-cat-taste-of-greek-language-and-culture-host", source: "course-taste-greek-language-and-culture", target: "university-uoc", type: "hosted_by", label: "Hosted by", explanation: "Α taste of Greek Language and Culture is associated with this partner's language and culture offer.", sourceIds: ["fc-cat-taste-of-greek-language-and-culture"], dataClassification: "verified" },
  { id: "rel-cat-contributions-annual-call", source: "opportunity-course-catalogue-contributions-2026", target: "opportunity-annual-education-call-2026", type: "part_of", label: "Part of", explanation: "Course Catalogue Contributions is one proposal route within the 2026/27 Annual Education Call.", sourceIds: ["fc-cat-course-catalogue-contributions-2026", "fc29-annual-education-call"], dataClassification: "verified" },
];
