import type { DataClassification, Entity, Relationship, Source } from "./data";

export const EXHAUSTIVE_RESEARCH_DATE = "2026-09-29";

const allUniversityIds = [
  "university-mtu",
  "university-hka",
  "university-xamk",
  "university-hs",
  "university-uoc",
  "university-mus",
  "university-uniovi",
  "university-urn",
  "university-uda",
  "university-tuiasi",
];

export const exhaustiveResearchSources: Source[] = [
  {
    id: "fc-full-bi4e-cordis",
    title: "Boosting INGENIUM for Excellence (BI4E)",
    kind: "European Commission CORDIS project report",
    url: "https://cordis.europa.eu/project/id/101071321/reporting",
    publisher: "European Commission",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "Project 101071321 involved eight INGENIUM higher-education institutions. The wider alliance has ten members; these scopes must not be conflated.",
  },
  {
    id: "fc-full-connect",
    title: "CONNECT researcher-matching platform",
    kind: "Official partner-hosted platform",
    url: "https://connect.unich.it/",
    publisher: "University G. d’Annunzio of Chieti-Pescara",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "BI4E and alliance calls identify CONNECT as a researcher-matching service. Public usage metrics were not found.",
  },
  {
    id: "fc-full-digital-wellbeing",
    title: "The First INGENIUM Shared Module: Digital Wellbeing",
    kind: "Official INGENIUM results article",
    url: "https://ingenium-university.eu/the-first-ingenium-shared-module-digital-wellbeing-a-milestone-for-the-alliance/",
    publisher: "INGENIUM European University",
    published: "November 2024",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-first-microcredential",
    title: "INGENIUM launches its first joint micro-credential",
    kind: "Official INGENIUM course announcement",
    url: "https://ingenium-university.eu/ingenium-launches-its-first-joint-micro-credential/",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-ambassadors",
    title: "INGENIUM Ambassadors Call 2026-2027",
    kind: "Official INGENIUM call",
    url: "https://ingenium-university.eu/ingenium-ambassadors-call-2026-2027/",
    publisher: "INGENIUM European University",
    published: "September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-eco-genium",
    title: "Eco-GENIUM: Eco-driven Digital & Manufacturing Innovation and Entrepreneurship",
    kind: "Official TUIASI project announcement",
    url: "https://www.tuiasi.ro/news/gheorghe-asachi-technical-university-of-iasi-involved-in-eco-genium-a-new-european-project-for-innovation-and-entrepreneurship-within-the-ingenium-alliance/?lang=en",
    publisher: "Gheorghe Asachi Technical University of Iași",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-green-genium",
    title: "GreenGenium: A Week of Sustainability and Collaboration at TUIASI",
    kind: "Official TUIASI project outcome",
    url: "https://international.tuiasi.ro/greengenium-a-week-of-sustainability-and-collaboration-at-tuiasi-within-the-ingenium-student-partnerships/",
    publisher: "Gheorghe Asachi Technical University of Iași",
    published: "21 October 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-urn-research-results",
    title: "Success of INGENIUM research-project calls at Rouen",
    kind: "Official University of Rouen Normandy results article",
    url: "https://www.univ-rouen.fr/actualites/belle-reussite-pour-les-appels-a-projet-de-lalliance-ingenium/",
    publisher: "University of Rouen Normandy",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-final-student-conference",
    title: "The Final INGENIUM Student Conference — Oviedo 2026",
    kind: "Official Medical University Sofia student call",
    url: "https://mu-sofia.bg/pokana-za-studenti-uchastie-v-the-final-ingenium-student-conferenc/",
    publisher: "Medical University Sofia",
    published: "23 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-taste-courses",
    title: "A Taste of INGENIUM Cultures and Languages Courses",
    kind: "Official INGENIUM learning announcement",
    url: "https://ingenium-university.eu/start-a-taste-of-ingenium-cultures-and-languages-courses/",
    publisher: "INGENIUM European University",
    published: "September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-inclusive-assessment",
    title: "Rethinking Inclusive Assessment in Higher Education",
    kind: "Official INGENIUM course page",
    url: "https://ingenium-university.eu/rethinking-inclusive-assessment-in-higher-education-assessment-as-learning-in-the-age-of-ai/",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-chess-club",
    title: "Play, Learn, Connect: Join the INGENIUM Chess Club",
    kind: "Official INGENIUM community announcement",
    url: "https://ingenium-university.eu/play-learn-connect-join-the-ingenium-chess-club/",
    publisher: "INGENIUM European University",
    published: "15 January 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-rouen-council",
    title: "INGENIUM Meets in Rouen to Plan a More Durable Phase",
    kind: "Official INGENIUM governance article",
    url: "https://ingenium-university.eu/ingenium-meets-in-rouen-to-plan-a-more-durable-phase-of-european-university-cooperation/",
    publisher: "INGENIUM European University",
    published: "16 June 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-governance",
    title: "INGENIUM Governance",
    kind: "Official INGENIUM governance page",
    url: "https://ingenium-university.eu/about-us/governance/",
    publisher: "INGENIUM European University",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-tuiasi-it4t",
    title: "INGENIUM Pathway for Information Technologies for Telecommunications",
    kind: "Official TUIASI faculty pathway page",
    url: "https://etti.tuiasi.ro/2026/09/17/ingenium-pathway-un-parcurs-international-pentru-studentii-masterului-it4t/",
    publisher: "Gheorghe Asachi Technical University of Iași",
    published: "17 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-tuiasi-aecs",
    title: "INGENIUM Pathway for Automotive Electronic Control Systems",
    kind: "Official TUIASI faculty pathway page",
    url: "https://etti.tuiasi.ro/2026/09/16/ingenium-pathway-un-parcurs-international-pentru-studentii-masterului-aecs/",
    publisher: "Gheorghe Asachi Technical University of Iași",
    published: "16 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d22",
    title: "D2.2 — INGENIUM Joint QA Policy",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/01/D2.2-QA-Policy.pdf",
    publisher: "INGENIUM European University",
    published: "2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d33",
    title: "D3.3 — INGENIUM Platforms",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2024/12/Deliverable_3.3_Final_v1.7.pdf",
    publisher: "INGENIUM European University",
    published: "December 2024; later revision metadata is inconsistent",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The public filename, internal version and later strategic-resource listing disagree. The conflict is retained.",
  },
  {
    id: "fc-full-d34",
    title: "D3.4 — Open Data & Open Science Repository v1",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2026/04/Deliverable_3.4_Open-Data-Open-Science-Repository-v.1.pdf",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d35",
    title: "D3.5 — Open Data & Open Science Repository",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2026/07/Deliverable_3.5_Open-Data-Open-Science-Repository-v.3.pdf",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The progress report calls this v2 while the public filename says v3.",
  },
  {
    id: "fc-full-d41",
    title: "D4.1 — Joint Programmes Report",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/D-4.1-Resubmitted-October-2025_compressed.pdf",
    publisher: "INGENIUM European University",
    published: "October 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d51",
    title: "D5.1 — Report on INGENIUM Innovation Strategy",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2024/06/D5.1-Report-on-INGENIUM-Innovation-Strategy.pdf",
    publisher: "INGENIUM European University",
    published: "April 2024",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d53",
    title: "D5.3 — INGENIUM Staff Academy Workshop 1",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/Deliverable-5.3-INGENIUM-Staff-Academy.pdf",
    publisher: "INGENIUM European University",
    published: "Revised October 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d61",
    title: "D6.1 — Regulations for the INGENIUM Research School",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/D-6.1-Resubmitted-October-2025.pdf",
    publisher: "INGENIUM European University",
    published: "October 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d71",
    title: "D7.1 — INGENIUM SDG/EGD and Global Partnership Agenda",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2026/08/Deliverable-7.1-final.pdf",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The strategic-resource page reuses D7.1 for several separate sustainability artifacts; this record is the agenda itself.",
  },
  {
    id: "fc-full-sustainable-travel",
    title: "INGENIUM Sustainable Travel Instructions",
    kind: "Official INGENIUM guidance",
    url: "https://ingenium-university.eu/wp-content/uploads/2026/08/deliverable-7.1-INGENIUM-sustainable-travel-instructions.pdf",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-event-sustainability",
    title: "INGENIUM Event Sustainability Checklist",
    kind: "Official INGENIUM guidance",
    url: "https://ingenium-university.eu/wp-content/uploads/2026/08/deliverable-7.1-event-sustainability-checklist.pdf",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-digital-carbon",
    title: "Guidelines for Reducing Digital Carbon Footprint",
    kind: "Official INGENIUM guidance",
    url: "https://ingenium-university.eu/wp-content/uploads/2026/08/Guidelines-for-Reducing-Digital-Carbon-Footprint-INGENIUM.pdf",
    publisher: "INGENIUM European University",
    published: "2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d84",
    title: "D8.4 — Final Report on Transnational Incubation and Acceleration",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/D8.4-Resubmitted-November-2025.pdf",
    publisher: "INGENIUM European University",
    published: "November 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d91",
    title: "D9.1 — INGENIUM Action Plan for Equity and Inclusion",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2024/06/D9.1-INGENIUM-Action-Plan-for-Equity-and-Inclusion.pdf",
    publisher: "INGENIUM European University",
    published: "2024",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d92",
    title: "D9.2 — Better Integrated and Inclusive Educational System",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/D9.2-Resubmitted-November-2025_compressed.pdf",
    publisher: "INGENIUM European University",
    published: "November 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d93",
    title: "INGENIUM Policy on Multilingualism and Intercultural Understanding",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2024/06/INGENIUM-Policy-on-Multilingualism-and-Intercultural-Understanding.pdf",
    publisher: "INGENIUM European University",
    published: "2024",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d94",
    title: "D9.4 — INGENIUM for a Healthy Campus",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2024/06/D9.4_INGENIUM-for-a-Healthy-Campus.pdf",
    publisher: "INGENIUM European University",
    published: "2024",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-d101",
    title: "D10.1 — INGENIUM Long-term Strategy",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/D10.1-Submitted-November-2025_compressed.pdf",
    publisher: "INGENIUM European University",
    published: "November 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The official strategy includes a candid implementation-risk assessment and a 2025–2035 roadmap centred on the EGTC and deeper integration.",
  },
  {
    id: "fc-full-d102",
    title: "D10.2 — INGENIUM Dissemination and Exploitation Strategy",
    kind: "Official INGENIUM deliverable",
    url: "https://ingenium-university.eu/wp-content/uploads/2025/12/D10.2-INGENIUM-Dissemination-and-Exploitation-Strategy-Revised-October-2025_compressed_compressed.pdf",
    publisher: "INGENIUM European University",
    published: "October 2025",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The 2025 revision moves exploitation planning into D10.1 and updates communication KPIs for 2025–2026.",
  },
  {
    id: "fc-full-mus-student-language-tandem-2026",
    title: "INGENIUM student linguistic-tandem programme 2026",
    kind: "Official Medical University Sofia call",
    url: "https://mu-sofia.bg/lingvistichna-tandemna-programa-po-proekt-ingenium/",
    publisher: "Medical University Sofia",
    published: "5 February 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "Bulgarian-language primary source. The 28 February 2026 deadline is historical; the programme is retained as evidence for the alliance language-network activity.",
  },
  {
    id: "fc-full-mus-staff-language-tandem-2026",
    title: "INGENIUM staff linguistic-tandem edition",
    kind: "Official Medical University Sofia programme announcement",
    url: "https://mu-sofia.bg/lingvistichen-tandem-izdanie-za-personala/",
    publisher: "Medical University Sofia",
    published: "21 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-mus-research-call-2026",
    title: "Call for joint INGENIUM research-group projects",
    kind: "Official Medical University Sofia research call",
    url: "https://mu-sofia.bg/pokana-za-savmestni-proekt-na-izsledovatelski-grupi-v-ramkite-na-ingenium/",
    publisher: "Medical University Sofia",
    published: "30 March 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-mus-innovation-course-2026",
    title: "Innovation Management and Entrepreneurship registration announcement",
    kind: "Official Medical University Sofia course announcement",
    url: "https://mu-sofia.bg/kursat-upravlenie-na-inovaciite-i-predpriemachestvo-na-ingenium-veche-e-otvoren-za-registracia/",
    publisher: "Medical University Sofia",
    published: "18 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-uoc-futureproof-2026",
    title: "FutureProof students put sustainability into action at Crete",
    kind: "Official University of Crete project outcome",
    url: "https://www.uoc.gr/en/futureproof-project-ingenium-students-put-sustainability-into-action-at-the-university-of-crete/",
    publisher: "University of Crete",
    published: "24 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-uoc-methodologies-2026",
    title: "14 innovative teaching and learning methodologies developed in INGENIUM",
    kind: "Official University of Crete education outcome",
    url: "https://www.uoc.gr/en/14-innovative-teaching-and-learning-methodologies-developed-in-ingenium-join-the-webinars-to-learn-more/",
    publisher: "University of Crete",
    published: "5 August 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-xamk-study-skills-bip",
    title: "Study-skills development BIP in Savonlinna",
    kind: "Official Xamk BIP outcome",
    url: "https://www.xamk.fi/en/study-skills-development-bip-by-ingenium-visited-savonlinna-for-a-week/",
    publisher: "South-Eastern Finland University of Applied Sciences",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The retrieved official page did not expose a reliable publication year or year for the stated 20 August application deadline, so no live deadline is inferred.",
  },
  {
    id: "fc-full-uda-lm37-pathway-2026",
    title: "INGENIUM Pathway for Languages, Literatures and Modern Cultures LM-37",
    kind: "Official University G. d'Annunzio pathway announcement",
    url: "https://www.unich.it/notizie/pathway-ingenium-percorso-accademico-internazionale-gli-studenti-di-lingue-lm37",
    publisher: "University G. d'Annunzio of Chieti-Pescara",
    published: "28 July 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-uda-lm37-call-2026",
    title: "LM-37 INGENIUM Pathway call 2026/27",
    kind: "Official Ud'A departmental pathway call",
    url: "https://www.lingue.unich.it/avvisi/pathway-ingenium-laurea-magistrale-lingue-letterature-e-culture-moderne-lm-37-aa-2026-2027",
    publisher: "University G. d'Annunzio of Chieti-Pescara",
    published: "10 July 2026; page date 20 September 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The source states a 20 September 2026 deadline, which had passed at the research cut-off.",
  },
  {
    id: "fc-full-mtu-innovation-challenge-2026",
    title: "MTU Innovation Challenge 2026 outcome",
    kind: "Official Munster Technological University news",
    url: "https://www.mtu.ie/news/2026/innovation-challenge-2026/",
    publisher: "Munster Technological University",
    published: "31 March 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
  },
  {
    id: "fc-full-uniovi-cbpt-master-2026",
    title: "First official INGENIUM joint master's programme approved",
    kind: "Official University of Oviedo programme announcement",
    url: "https://www.uniovi.es/actualidad/noticias/-/asset_publisher/Ru0cAJNPrm1m/content/la-alianza-europea-ingenium-pondr%25C3%25A1-en-marcha-el-pr%25C3%25B3ximo-curso-acad%C3%A9mico-su-primer-m%C3%A1ster-oficial",
    publisher: "University of Oviedo",
    published: "6 April 2026",
    verifiedAt: EXHAUSTIVE_RESEARCH_DATE,
    notes: "The April source described accreditation and capacity as pending; later July 2026 sources report accreditation completed and enrolment under way.",
  },
];

type ExhaustiveEntityInput = Omit<Entity, "lastVerified" | "dataClassification" | "confidence"> & {
  confidence?: Entity["confidence"];
  dataClassification?: DataClassification;
};

function verifiedEntity(input: ExhaustiveEntityInput): Entity {
  return {
    ...input,
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
    confidence: input.confidence ?? "High",
    dataClassification: input.dataClassification ?? "verified",
    sourceIds: input.sourceIds ?? [input.sourceId],
  };
}

const activityEntities: Entity[] = [
  verifiedEntity({
    id: "project-bi4e",
    slug: "boosting-ingenium-for-excellence",
    title: "Boosting INGENIUM for Excellence",
    shortTitle: "BI4E",
    type: "project",
    subtype: "Horizon Europe institutional-transformation project",
    studentSummary: "A Horizon Europe project that strengthened research, innovation, governance, technology transfer and academic careers across eight INGENIUM institutions.",
    fullDescription: "Project 101071321 ran from October 2022 through September 2025. Public outputs include institutional-transformation guidance, research-support policy, entrepreneurship and innovation-service resources, a technology-transfer-office network, talent studies, staff training and the CONNECT researcher-matching platform. Its eight-institution consortium is narrower than the ten-member alliance.",
    status: "Completed",
    availability: "Project results are public through CORDIS",
    universityIds: ["university-tuiasi", "university-hka", "university-hs", "university-mus", "university-mtu", "university-uda", "university-urn"],
    hostUniversityId: "university-tuiasi",
    themes: ["Research", "Innovation", "Institutional transformation", "Technology transfer"],
    startDate: "2022-10-01",
    endDate: "2025-09-30",
    dateLabel: "October 2022–September 2025",
    actionLabel: "Read the CORDIS results",
    officialUrl: "https://cordis.europa.eu/project/id/101071321/reporting",
    sourceId: "fc-full-bi4e-cordis",
    workPackage: "Horizon Europe project 101071321",
    featured: true,
  }),
  verifiedEntity({
    id: "platform-connect",
    slug: "connect-researcher-matching",
    title: "CONNECT Researcher-Matching Platform",
    shortTitle: "CONNECT",
    type: "platform",
    subtype: "Research collaboration service",
    studentSummary: "A partner-hosted service for discovering researchers, supervisors and potential cross-alliance collaborators.",
    fullDescription: "BI4E reports CONNECT as an AI-supported researcher-matching output, and official alliance calls direct researchers and doctoral candidates to it. Public uptake, accuracy and service-level metrics were not found.",
    status: "Ongoing",
    availability: "Public platform; access and coverage should be checked directly",
    universityIds: ["university-uda"],
    hostUniversityId: "university-uda",
    themes: ["Research", "Matchmaking", "Doctoral collaboration"],
    deliveryMode: "Online",
    actionLabel: "Open CONNECT",
    officialUrl: "https://connect.unich.it/",
    sourceId: "fc-full-connect",
    sourceIds: ["fc-full-connect", "fc-full-bi4e-cordis"],
  }),
  verifiedEntity({
    id: "module-digital-wellbeing-2024",
    slug: "digital-wellbeing-shared-module-2024",
    title: "Digital Wellbeing — First Shared INGENIUM Module",
    type: "module",
    subtype: "Blended shared module pilot",
    studentSummary: "The alliance’s first shared module combined online learning with an intensive week at MTU and tested common academic and digital-delivery processes.",
    fullDescription: "Development began in November 2023. Online lectures started in September 2024, followed by a week at Munster Technological University in October and completion in December. The 5-ECTS pilot involved 20 staff and 40 students across disciplines, used the INGENIUM Moodle platform and produced reusable resources for partner delivery.",
    status: "Completed",
    availability: "Historical pilot and reusable learning resources",
    universityIds: allUniversityIds,
    hostUniversityId: "university-mtu",
    countries: ["Ireland"],
    city: "Cork",
    themes: ["Digital wellbeing", "Shared education", "Blended learning"],
    deliveryMode: "Blended",
    mobilityType: "Online lectures plus one physical intensive week",
    startDate: "2024-09-01",
    endDate: "2024-12-31",
    dateLabel: "September–December 2024",
    ects: 5,
    capacity: "40 students and 20 staff",
    actionLabel: "Read the module outcome",
    officialUrl: "https://ingenium-university.eu/the-first-ingenium-shared-module-digital-wellbeing-a-milestone-for-the-alliance/",
    sourceId: "fc-full-digital-wellbeing",
  }),
  verifiedEntity({
    id: "microcredential-towards-framework-2026",
    slug: "towards-ingenium-microcredentials-framework-2026",
    title: "Towards INGENIUM Micro-credentials Framework",
    type: "microcredential",
    subtype: "First joint INGENIUM microcredential",
    studentSummary: "The first joint alliance microcredential trained staff to design, manage and certify joint microcredentials through the INGENIUM Education Platform.",
    fullDescription: "The pilot was jointly developed by Oviedo, Xamk and Crete. It combined asynchronous content, quizzes, a multinational group proposal and peer review, and demonstrated final digital certification through Europass.",
    status: "Completed",
    availability: "The first edition ran online from 11 May to 30 June 2026",
    universityIds: ["university-uniovi", "university-xamk", "university-uoc"],
    hostUniversityId: "university-uniovi",
    themes: ["Microcredentials", "Staff development", "Digital credentials"],
    deliveryMode: "Online",
    startDate: "2026-05-11",
    endDate: "2026-06-30",
    applicationOpenDate: "2026-04-27",
    applicationDeadline: "2026-05-03",
    dateLabel: "11 May–30 June 2026",
    ects: 1,
    workload: "25 hours: 14 teaching and 11 group work",
    eligibility: "Academic and administrative staff at INGENIUM universities, plus eligible external partners",
    capacity: "50 participants, maximum five per institution",
    actionLabel: "Read the pilot record",
    officialUrl: "https://ingenium-university.eu/ingenium-launches-its-first-joint-micro-credential/",
    sourceId: "fc-full-first-microcredential",
  }),
  verifiedEntity({
    id: "opportunity-ingenium-ambassadors-2026",
    slug: "ingenium-ambassadors-call-2026-2027",
    title: "INGENIUM Ambassadors Call 2026/2027",
    type: "opportunity",
    subtype: "Student communication-project call",
    studentSummary: "Students can propose communication projects that bring the alliance closer to their peers and include a funded exchange visit to another partner university.",
    fullDescription: "Projects are led by one student or a two-student team at the same partner university. The seven-month period runs from 1 November 2026 to 31 May 2027, followed by a final report and closing piece by the end of June.",
    status: "Opens soon",
    availability: "Applications open 1 October and close 18 October 2026 at 23:59 CET",
    universityIds: allUniversityIds,
    themes: ["Student voice", "Communication", "Mobility"],
    academicLevel: "Bachelor, Master or PhD",
    startDate: "2026-11-01",
    endDate: "2027-05-31",
    applicationOpenDate: "2026-10-01",
    applicationDeadline: "2026-10-18",
    eligibility: "One student or a team of two at the same participating university, with uninterrupted student status through the project period",
    funding: "Exchange visit funded up to €1,000 per team member",
    capacity: "At least one project per participating university, subject to local-office capacity",
    actionLabel: "Prepare an Ambassadors proposal",
    officialUrl: "https://ingenium-university.eu/ingenium-ambassadors-call-2026-2027/",
    sourceId: "fc-full-ambassadors",
    featured: true,
  }),
  verifiedEntity({
    id: "project-eco-genium",
    slug: "eco-genium",
    title: "Eco-GENIUM",
    type: "project",
    subtype: "EIT Higher Education Initiative project",
    studentSummary: "A two-year innovation-ecosystem project connecting six INGENIUM universities with business and teaching-factory partners.",
    fullDescription: "Eco-driven Digital & Manufacturing Innovation and Entrepreneurship for the INGENIUM Alliance was funded under the EIT HEI 2025 Building Synergies topic. It aims to create transferable governance, cooperation mechanisms and innovation pipelines that can spill over across the wider alliance.",
    status: "Ongoing",
    availability: "Funded 24-month consortium project",
    universityIds: ["university-hs", "university-uniovi", "university-mtu", "university-hka", "university-uda", "university-tuiasi"],
    hostUniversityId: "university-hs",
    themes: ["Innovation ecosystems", "Entrepreneurship", "Manufacturing", "Digital transformation"],
    workload: "24-month project",
    funding: "EIT Higher Education Initiative 2025 — Building Synergies",
    actionLabel: "Read the project announcement",
    officialUrl: "https://www.tuiasi.ro/news/gheorghe-asachi-technical-university-of-iasi-involved-in-eco-genium-a-new-european-project-for-innovation-and-entrepreneurship-within-the-ingenium-alliance/?lang=en",
    sourceId: "fc-full-eco-genium",
    featured: true,
  }),
  verifiedEntity({
    id: "project-green-genium",
    slug: "green-genium",
    title: "GreenGENIUM",
    type: "project",
    subtype: "Student Partnership sustainability project",
    studentSummary: "A student-led sustainability project that demonstrated campus composting, peer learning and cross-university collaboration at TUIASI.",
    fullDescription: "The official outcome documents a TUIASI visit, laboratory and composting learning, and the One Peel at a Time campus action. It is evidence of delivered activity rather than merely a proposed sustainability concept.",
    status: "Completed",
    availability: "Historical 2025 project outcome",
    universityIds: ["university-tuiasi"],
    hostUniversityId: "university-tuiasi",
    countries: ["Romania"],
    city: "Iași",
    themes: ["Sustainability", "Composting", "Student partnerships"],
    endDate: "2025-10-21",
    dateLabel: "October 2025",
    actionLabel: "Read the project outcome",
    officialUrl: "https://international.tuiasi.ro/greengenium-a-week-of-sustainability-and-collaboration-at-tuiasi-within-the-ingenium-student-partnerships/",
    sourceId: "fc-full-green-genium",
  }),
  verifiedEntity({
    id: "initiative-urn-ingenium-research-calls",
    slug: "rouen-ingenium-research-calls-2024-2026",
    title: "Rouen INGENIUM Research Project Calls 2024–2026",
    type: "initiative",
    subtype: "France 2030 and ANR-supported research portfolio",
    studentSummary: "Three University of Rouen calls financed 36 collaborative research projects with INGENIUM partners, including 17 selected in 2026.",
    fullDescription: "The University of Rouen Normandy used France 2030 funding administered through the French National Research Agency to run three successive alliance research calls. The third and final call of the first funding period selected 17 projects in 2026; 36 were funded across all three rounds.",
    status: "Completed",
    availability: "Results published for the first funding period",
    universityIds: ["university-urn"],
    hostUniversityId: "university-urn",
    countries: ["France"],
    city: "Rouen",
    themes: ["Research funding", "Joint projects", "France 2030"],
    startDate: "2024-01-01",
    endDate: "2026-12-31",
    dateLabel: "2024–2026",
    capacity: "36 projects across three calls; 17 selected in 2026",
    actionLabel: "Read the results",
    officialUrl: "https://www.univ-rouen.fr/actualites/belle-reussite-pour-les-appels-a-projet-de-lalliance-ingenium/",
    sourceId: "fc-full-urn-research-results",
  }),
  verifiedEntity({
    id: "event-final-student-conference-oviedo-2026",
    slug: "final-ingenium-student-conference-oviedo-2026",
    title: "Final INGENIUM Student Conference — Oviedo 2026",
    type: "event",
    subtype: "Alliance student conference",
    studentSummary: "A week in Oviedo combining the first four-year phase’s closing ceremony with workshops, practical learning and cross-alliance student exchange.",
    fullDescription: "Medical University Sofia’s local call offers five fully funded places to students from all faculties and units. That local deadline is 7 October 2026; other universities may use different routes and deadlines.",
    status: "Upcoming",
    availability: "MUS local applications close 7 October 2026",
    universityIds: allUniversityIds,
    hostUniversityId: "university-uniovi",
    countries: ["Spain"],
    city: "Oviedo",
    themes: ["Student conference", "Alliance community", "Mobility"],
    startDate: "2026-11-20",
    endDate: "2026-11-26",
    applicationDeadline: "2026-10-07",
    dateLabel: "20–26 November 2026",
    eligibility: "The cited local call covers Medical University Sofia students from all faculties and units",
    funding: "Full participation funding for selected MUS students",
    capacity: "Five MUS places in the cited local call",
    actionLabel: "Read the MUS call",
    officialUrl: "https://mu-sofia.bg/pokana-za-studenti-uchastie-v-the-final-ingenium-student-conferenc/",
    sourceId: "fc-full-final-student-conference",
    featured: true,
  }),
  verifiedEntity({
    id: "learning-resource-taste-cultures-languages",
    slug: "taste-of-ingenium-cultures-languages",
    title: "A Taste of INGENIUM Cultures and Languages",
    type: "learning_resource",
    subtype: "Pre-mobility language and culture courses",
    studentSummary: "Self-paced beginner courses introduce alliance languages and cultures for mobility preparation or independent intercultural learning.",
    fullDescription: "Eight courses are currently available: Finnish, French, German, Greek, Italian, Romanian, Spanish and Swedish. Bulgarian and Irish are announced as coming soon. The official page describes the resources as virtual and self-paced for students and staff.",
    status: "Ongoing",
    availability: "Eight languages live; Bulgarian and Irish announced",
    universityIds: allUniversityIds,
    themes: ["Languages", "Culture", "Mobility preparation"],
    deliveryMode: "Online, self-paced",
    eligibility: "INGENIUM students and staff",
    languages: ["Finnish", "French", "German", "Greek", "Italian", "Romanian", "Spanish", "Swedish"],
    actionLabel: "Explore the language courses",
    officialUrl: "https://ingenium-university.eu/start-a-taste-of-ingenium-cultures-and-languages-courses/",
    sourceId: "fc-full-taste-courses",
  }),
  verifiedEntity({
    id: "community-ingenium-chess-club",
    slug: "ingenium-chess-club",
    title: "INGENIUM Chess Club",
    type: "community",
    subtype: "Online cross-alliance club",
    studentSummary: "An online Chess.com community for friendly games, tournaments, challenges and inter-university representation.",
    status: "Ongoing",
    availability: "Open to students and staff",
    universityIds: allUniversityIds,
    themes: ["Community", "Chess", "Intercultural connection"],
    startDate: "2026-01-15",
    deliveryMode: "Online via Chess.com",
    eligibility: "Students and staff across the INGENIUM partner universities",
    actionLabel: "Read the joining instructions",
    officialUrl: "https://ingenium-university.eu/play-learn-connect-join-the-ingenium-chess-club/",
    sourceId: "fc-full-chess-club",
  }),
  verifiedEntity({
    id: "event-alliance-council-rouen-2026",
    slug: "alliance-council-rouen-2026",
    title: "INGENIUM Alliance Council Meeting — Rouen 2026",
    type: "event",
    subtype: "Alliance governance meeting",
    studentSummary: "Alliance leaders met in Rouen to prepare durable cooperation beyond the first funding phase and advance joint education and the EGTC.",
    fullDescription: "The meeting confirmed the first European Approach accreditation for CBPT in Romania, recorded progress on SMAC² and set first-year EGTC priorities: securing funding, representing the alliance and coordinating the annual education cycle.",
    status: "Completed",
    availability: "Historical governance meeting",
    universityIds: allUniversityIds,
    hostUniversityId: "university-urn",
    countries: ["France"],
    city: "Rouen",
    themes: ["Governance", "Joint programmes", "EGTC"],
    startDate: "2026-06-16",
    dateLabel: "16 June 2026",
    actionLabel: "Read the council outcome",
    officialUrl: "https://ingenium-university.eu/ingenium-meets-in-rouen-to-plan-a-more-durable-phase-of-european-university-cooperation/",
    sourceId: "fc-full-rouen-council",
  }),
  verifiedEntity({
    id: "opportunity-mus-joint-research-call-2026",
    slug: "mus-joint-research-project-call-2026",
    title: "Medical University Sofia Joint Research-Project Call 2026",
    type: "opportunity",
    subtype: "Archived cross-alliance research call",
    studentSummary: "A documented Medical University Sofia call supported joint research groups developing workshops, webinars and microcredentials with alliance partners.",
    fullDescription: "The official Bulgarian-language call invited interdisciplinary or specialised joint research-group projects and offered up to €10,000 per project. The application deadline was 19 April 2026, so this is retained as a historical funding record rather than shown as open.",
    status: "Closed",
    availability: "Archived call; deadline was 19 April 2026",
    universityIds: allUniversityIds,
    hostUniversityId: "university-mus",
    countries: ["Bulgaria"],
    city: "Sofia",
    themes: ["Research", "Microcredentials", "Staff collaboration"],
    applicationDeadline: "2026-04-19",
    funding: "Up to €10,000 per project",
    eligibility: "Joint research groups involving INGENIUM partner universities",
    actionLabel: "Read the archived call",
    officialUrl: "https://mu-sofia.bg/pokana-za-savmestni-proekt-na-izsledovatelski-grupi-v-ramkite-na-ingenium/",
    sourceId: "fc-full-mus-research-call-2026",
  }),
  verifiedEntity({
    id: "learning-resource-ingenium-methodologies-2026",
    slug: "fourteen-ingenium-teaching-methodologies",
    title: "14 INGENIUM Teaching and Learning Methodologies",
    type: "learning_resource",
    subtype: "Alliance education-methodology collection",
    studentSummary: "A University of Crete evidence page records fourteen teaching and learning methodologies developed across INGENIUM and shared through webinars.",
    status: "Completed",
    availability: "Published education outcome and webinar resource",
    universityIds: allUniversityIds,
    hostUniversityId: "university-uoc",
    themes: ["Teaching innovation", "Learning design", "Staff development"],
    actionLabel: "Explore the methodologies",
    officialUrl: "https://www.uoc.gr/en/14-innovative-teaching-and-learning-methodologies-developed-in-ingenium-join-the-webinars-to-learn-more/",
    sourceId: "fc-full-uoc-methodologies-2026",
    workPackage: "WP5",
  }),
  verifiedEntity({
    id: "bip-study-skills-savonlinna",
    slug: "study-skills-development-savonlinna",
    title: "Study Skills Development BIP — Savonlinna",
    type: "bip",
    subtype: "Interdisciplinary blended intensive programme",
    studentSummary: "A Xamk-hosted BIP brought INGENIUM students to Savonlinna for an intensive week focused on study-skills development.",
    fullDescription: "Xamk reports the delivered intensive week and says its degree students could apply to three interdisciplinary INGENIUM BIPs. The retrieved page does not expose a reliable publication year or year for its relative 20 August deadline, so the activity is documented without presenting that deadline as current.",
    status: "Completed",
    availability: "Historical delivery; future editions require direct confirmation",
    universityIds: allUniversityIds,
    hostUniversityId: "university-xamk",
    countries: ["Finland"],
    city: "Savonlinna",
    themes: ["Study skills", "Student wellbeing", "Mobility"],
    deliveryMode: "Blended",
    mobilityType: "Physical intensive week plus a virtual component",
    actionLabel: "Read the Xamk outcome",
    officialUrl: "https://www.xamk.fi/en/study-skills-development-bip-by-ingenium-visited-savonlinna-for-a-week/",
    sourceId: "fc-full-xamk-study-skills-bip",
    confidence: "Medium",
  }),
  verifiedEntity({
    id: "pathway-languages-lm37",
    slug: "languages-literatures-modern-cultures-lm37-pathway",
    title: "Languages, Literatures and Modern Cultures LM-37 Pathway",
    type: "pathway",
    subtype: "International master's pathway",
    studentSummary: "A language-and-culture master's pathway links Ud'A with Oviedo, Rouen and Xamk through mobility, international learning, BIPs and challenge-based activity.",
    fullDescription: "The 2026/27 departmental call states that the pathway includes at least 25% physical Erasmus+ mobility and 25% international learning. It is embedded in the LM-37 master's degree and can include BIPs, partner mobility and challenge-based mobility. The 20 September 2026 call deadline is now closed.",
    status: "Ongoing",
    availability: "2026/27 pathway confirmed; cited local call closed 20 September 2026",
    universityIds: ["university-uda", "university-uniovi", "university-urn", "university-xamk"],
    hostUniversityId: "university-uda",
    countries: ["Italy", "Spain", "France", "Finland"],
    themes: ["Languages", "Culture", "Mobility", "Challenge-based learning"],
    studyLevels: ["Master"],
    applicationDeadline: "2026-09-20",
    workload: "At least 25% physical mobility and 25% international learning",
    actionLabel: "View the official pathway",
    officialUrl: "https://www.unich.it/notizie/pathway-ingenium-percorso-accademico-internazionale-gli-studenti-di-lingue-lm37",
    sourceId: "fc-full-uda-lm37-pathway-2026",
    sourceIds: ["fc-full-uda-lm37-pathway-2026", "fc-full-uda-lm37-call-2026"],
  }),
];

type DeliverableInput = {
  id: string;
  slug: string;
  title: string;
  sourceId: string;
  workPackage: string;
  summary: string;
  themes: string[];
};

const deliverableInputs: DeliverableInput[] = [
  { id: "learning-resource-qa-policy-d22", slug: "joint-qa-policy-d22", title: "D2.2 — INGENIUM Joint QA Policy", sourceId: "fc-full-d22", workPackage: "WP2", summary: "The alliance’s public joint quality-assurance policy for its inter-university campus and shared education.", themes: ["Quality assurance", "Joint education", "Governance"] },
  { id: "learning-resource-platforms-d33", slug: "ingenium-platforms-d33", title: "D3.3 — INGENIUM Platforms", sourceId: "fc-full-d33", workPackage: "WP3", summary: "The implementation record for the public front portal, Moodle Education Platform, Intra-Alliance site and shared digital services.", themes: ["Digital infrastructure", "Moodle", "Interoperability"] },
  { id: "learning-resource-open-data-d34", slug: "open-data-repository-d34", title: "D3.4 — Open Data & Open Science Repository v1", sourceId: "fc-full-d34", workPackage: "WP3", summary: "The first public deliverable documenting the alliance Open Data and Open Science repository.", themes: ["Open science", "Research infrastructure", "Repository"] },
  { id: "learning-resource-open-data-d35", slug: "open-data-repository-d35", title: "D3.5 — Open Data & Open Science Repository", sourceId: "fc-full-d35", workPackage: "WP3", summary: "A later repository deliverable whose public filename says v3 while the progress register calls the planned output v2.", themes: ["Open science", "Research infrastructure", "Version conflict"] },
  { id: "learning-resource-joint-programmes-d41", slug: "joint-programmes-report-d41", title: "D4.1 — Joint Programmes Report", sourceId: "fc-full-d41", workPackage: "WP4", summary: "The principal evidence register for joint degrees, double degrees and the original Pathway pilot portfolio.", themes: ["Joint programmes", "Pathways", "European campus"] },
  { id: "learning-resource-innovation-strategy-d51", slug: "innovation-strategy-d51", title: "D5.1 — INGENIUM Innovation Strategy", sourceId: "fc-full-d51", workPackage: "WP5", summary: "The alliance framework for educational innovation, the Education Lab, Staff Academy and transfer of teaching practice.", themes: ["Innovation", "Teaching", "Education Lab"] },
  { id: "learning-resource-staff-academy-d53", slug: "staff-academy-workshop-d53", title: "D5.3 — INGENIUM Staff Academy Workshop 1", sourceId: "fc-full-d53", workPackage: "WP5", summary: "The first public Staff Academy workshop deliverable, later revised during the 2025 resubmission cycle.", themes: ["Staff development", "Teaching innovation", "Training"] },
  { id: "learning-resource-research-school-d61", slug: "research-school-regulations-d61", title: "D6.1 — Regulations for the INGENIUM Research School", sourceId: "fc-full-d61", workPackage: "WP6", summary: "The public regulatory basis for the alliance research-school and doctoral ecosystem model.", themes: ["Research school", "Doctoral education", "Regulation"] },
  { id: "learning-resource-sdg-agenda-d71", slug: "sdg-egd-agenda-d71", title: "D7.1 — SDG/EGD and Global Partnership Agenda", sourceId: "fc-full-d71", workPackage: "WP7", summary: "The central sustainable-development, European Green Deal and global-partnership agenda for the alliance.", themes: ["Sustainability", "SDGs", "European Green Deal"] },
  { id: "learning-resource-sustainable-travel", slug: "sustainable-travel-instructions", title: "INGENIUM Sustainable Travel Instructions", sourceId: "fc-full-sustainable-travel", workPackage: "WP7", summary: "Practical guidance for reducing the impact of alliance travel and mobility.", themes: ["Sustainable travel", "Mobility", "Climate"] },
  { id: "learning-resource-event-sustainability", slug: "event-sustainability-checklist", title: "INGENIUM Event Sustainability Checklist", sourceId: "fc-full-event-sustainability", workPackage: "WP7", summary: "A practical checklist for embedding environmental and social sustainability in alliance events.", themes: ["Sustainable events", "Operations", "Climate"] },
  { id: "learning-resource-digital-carbon", slug: "digital-carbon-footprint-guidelines", title: "Guidelines for Reducing Digital Carbon Footprint", sourceId: "fc-full-digital-carbon", workPackage: "WP7", summary: "Alliance guidance for reducing the environmental impact of digital work, services and communication.", themes: ["Digital sustainability", "Carbon", "Guidance"] },
  { id: "learning-resource-acceleration-d84", slug: "incubation-acceleration-d84", title: "D8.4 — Transnational Incubation and Acceleration Programme", sourceId: "fc-full-d84", workPackage: "WP8", summary: "The final public report on the alliance accelerator, incubation and Soft Landings development work.", themes: ["Entrepreneurship", "Acceleration", "Incubation"] },
  { id: "learning-resource-equity-action-d91", slug: "equity-inclusion-action-plan-d91", title: "D9.1 — Action Plan for Equity and Inclusion", sourceId: "fc-full-d91", workPackage: "WP9", summary: "The alliance action plan for equity, inclusion, diversity and accessibility.", themes: ["Equity", "Inclusion", "Accessibility"] },
  { id: "learning-resource-inclusive-system-d92", slug: "integrated-inclusive-system-d92", title: "D9.2 — Better Integrated and Inclusive Educational System", sourceId: "fc-full-d92", workPackage: "WP9", summary: "The revised public deliverable on building a more integrated and inclusive alliance education system.", themes: ["Inclusive education", "Integration", "Accessibility"] },
  { id: "learning-resource-multilingualism-d93", slug: "multilingualism-policy-d93", title: "INGENIUM Policy on Multilingualism and Intercultural Understanding", sourceId: "fc-full-d93", workPackage: "WP9", summary: "The alliance policy connecting multilingualism, mobility and intercultural understanding.", themes: ["Multilingualism", "Culture", "Mobility"] },
  { id: "learning-resource-healthy-campus-d94", slug: "healthy-campus-d94", title: "D9.4 — INGENIUM for a Healthy Campus", sourceId: "fc-full-d94", workPackage: "WP9", summary: "The core public deliverable behind the alliance Healthy Campus guidelines and toolkit.", themes: ["Wellbeing", "Healthy campus", "Inclusion"] },
  { id: "learning-resource-long-term-strategy-d101", slug: "long-term-strategy-d101", title: "D10.1 — INGENIUM Long-term Strategy", sourceId: "fc-full-d101", workPackage: "WP10", summary: "The 2025–2035 strategy, including the EGTC roadmap, European-degree ambition and a candid assessment of implementation risks.", themes: ["Strategy", "EGTC", "European degree"] },
  { id: "learning-resource-dissemination-d102", slug: "dissemination-strategy-d102", title: "D10.2 — Dissemination and Exploitation Strategy", sourceId: "fc-full-d102", workPackage: "WP10", summary: "The revised communication and dissemination framework and its 2025–2026 KPI model.", themes: ["Communication", "Dissemination", "KPIs"] },
];

const deliverableEntities: Entity[] = deliverableInputs.map((item) => verifiedEntity({
  id: item.id,
  slug: item.slug,
  title: item.title,
  type: "learning_resource",
  subtype: "Official INGENIUM deliverable",
  studentSummary: item.summary,
  status: "Completed",
  availability: "Public evidence resource",
  universityIds: allUniversityIds,
  themes: item.themes,
  actionLabel: "Open the official deliverable",
  officialUrl: exhaustiveResearchSources.find((source) => source.id === item.sourceId)?.url,
  sourceId: item.sourceId,
  workPackage: item.workPackage,
}));

export const exhaustiveResearchEntities: Entity[] = [
  ...activityEntities,
  ...deliverableEntities,
];

export const exhaustiveResearchOverrides: Partial<Record<string, Partial<Entity>>> = {
  "initiative-ilanet-language-network": {
    status: "Ongoing",
    availability: "Student and staff linguistic-tandem editions were documented by Medical University Sofia in 2026",
    fullDescription: "ILANET connects self-paced pre-mobility language resources with reciprocal peer tandems. Medical University Sofia's official 2026 pages independently verify a student edition open alliance-wide and a later staff edition, resolving the earlier reliance on a future-dated HKA description.",
    officialUrl: "https://mu-sofia.bg/lingvistichen-tandem-izdanie-za-personala/",
    sourceId: "fc-full-mus-staff-language-tandem-2026",
    sourceIds: ["fc-ilanet-2026", "fc-full-mus-student-language-tandem-2026", "fc-full-mus-staff-language-tandem-2026", "fc-full-taste-courses"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "course-innovation-management-entrepreneurship": {
    status: "Ongoing",
    availability: "The free ten-week online course began 29 September 2026; the cited registration deadline was 25 September",
    fullDescription: "A free ten-week online accelerator course for students and staff across the alliance. The Medical University Sofia announcement confirms weekly live lectures, a 29 September 2026 start and a digital badge for successful completion.",
    startDate: "2026-09-29",
    applicationDeadline: "2026-09-25",
    workload: "Ten weeks with weekly live lectures",
    eligibility: "Students and staff of the ten INGENIUM universities",
    actionLabel: "Read the confirmed course announcement",
    officialUrl: "https://mu-sofia.bg/kursat-upravlenie-na-inovaciite-i-predpriemachestvo-na-ingenium-veche-e-otvoren-za-registracia/",
    sourceId: "fc-full-mus-innovation-course-2026",
    sourceIds: ["course-catalogue-2026", "fc-full-mus-innovation-course-2026"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "initiative-innovation-challenge": {
    status: "Ongoing",
    availability: "The 2026 edition concluded on 12 March after an eight-week programme",
    fullDescription: "The 2026 edition involved ten student teams working with European and African university, healthcare and community partners on healthcare, assistive-technology, sustainability and digital-innovation challenges. Two teams received €1,000 prizes and all participants received a digital badge.",
    universityIds: ["university-mtu", "university-uoc", "university-urn"],
    hostUniversityId: "university-mtu",
    capacity: "Ten teams across MTU's six Cork and Kerry campuses, with international partners",
    funding: "Two €1,000 team prizes in the 2026 edition",
    actionLabel: "Read the 2026 outcome",
    officialUrl: "https://www.mtu.ie/news/2026/innovation-challenge-2026/",
    sourceId: "fc-full-mtu-innovation-challenge-2026",
    sourceIds: ["entrepreneurship-training", "fc-full-mtu-innovation-challenge-2026"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "project-futureproof": {
    availability: "Implementation documented through a three-day University of Crete session on 2–4 September 2026",
    fullDescription: "The funded student partnership tested its Sustainable Escape Room in Heraklion and combined it with biodiversity, pollinator and climate-action activities. Related partner reports document the wider Student Sustainability Hub, toolkit and action-roadmap work.",
    officialUrl: "https://www.uoc.gr/en/futureproof-project-ingenium-students-put-sustainability-into-action-at-the-university-of-crete/",
    sourceId: "fc-full-uoc-futureproof-2026",
    sourceIds: ["student-partnerships-2026", "fc-full-uoc-futureproof-2026"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "programme-cbpt": {
    status: "Ongoing",
    availability: "Accredited for 2026/27; later official sources report enrolment under way",
    fullDescription: "The 120-ECTS, two-year international joint master's programme rotates study across Iași, Oviedo and Rouen, with internships and the master's thesis at a chosen partner. Oviedo's April 2026 approval described an expected cohort of 10–30; later July sources report European Approach accreditation completed and students enrolling.",
    universityIds: ["university-tuiasi", "university-uniovi", "university-urn"],
    startDate: "2026-09-01",
    ects: 120,
    capacity: "Expected cohort of 10–30 students in the April 2026 approval record",
    actionLabel: "View the official joint-master record",
    officialUrl: "https://www.uniovi.es/actualidad/noticias/-/asset_publisher/Ru0cAJNPrm1m/content/la-alianza-europea-ingenium-pondr%25C3%25A1-en-marcha-el-pr%25C3%25B3ximo-curso-acad%C3%A9mico-su-primer-m%C3%A1ster-oficial",
    sourceId: "fc-full-uniovi-cbpt-master-2026",
    sourceIds: ["joint-master-cbpt", "fc-full-uniovi-cbpt-master-2026", "fc-full-rouen-council"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "bip-digital-health": {
    status: "Upcoming",
    availability: "Virtual sessions run 5–24 October 2026; the physical week is 12–18 April 2027 at the University of Skövde. Local application deadlines vary.",
    startDate: "2026-10-05",
    endDate: "2027-04-18",
    dateLabel: "Virtual: 5–24 October 2026; Skövde: 12–18 April 2027",
    capacity: "Up to 30 students; normally two to five from each coordinating or sending partner",
    fullDescription: "A 3-ECTS interdisciplinary BIP in digital health, welfare technology, informatics, engineering and person-centred care. The physical component at Skövde runs for five days and 40 on-site hours. Students apply through their home institution and typically need B2 English.",
    officialUrl: "https://ingenium-university.eu/event/bip-multidisciplinary-approaches-to-digital-competence-and-innovation-in-health-care/",
    sourceId: "fc29-bips-2026-2027",
    sourceIds: ["bips-2627", "fc29-bips-2026-2027"],
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "pathway-telecommunications-it": {
    status: "Ongoing",
    statusOverride: undefined,
    availability: "The 2026–2028 IT4T cohort pathway is confirmed; its local expression-of-interest deadline was 25 September 2026",
    fullDescription: "The route begins with the Sustainable Development & Corporate Responsibility BIP at Crete, includes semester 3 at the University of Skövde through Data Science and Cybersecurity modules, supports international projects and can lead to a jointly supervised dissertation.",
    applicationDeadline: "2026-09-25",
    mobilityType: "BIP, semester mobility at Skövde, international projects and possible co-supervised dissertation",
    actionLabel: "View the confirmed TUIASI pathway",
    officialUrl: "https://etti.tuiasi.ro/2026/09/17/ingenium-pathway-un-parcurs-international-pentru-studentii-masterului-it4t/",
    sourceId: "fc-full-tuiasi-it4t",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live", "fc-full-tuiasi-it4t"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "pathway-automotive-electronics": {
    status: "Ongoing",
    statusOverride: undefined,
    availability: "The 2026–2028 AECS cohort pathway is confirmed; its local expression-of-interest deadline was 25 September 2026",
    fullDescription: "The route starts with the Sustainable Development & Corporate Responsibility BIP at Crete and includes a 30-ECTS semester at Munster Technological University in autumn 2027. International teamwork, possible dissertation co-supervision and a short dissertation-preparation mobility can be included.",
    applicationDeadline: "2026-09-25",
    workload: "A 30-ECTS semester at MTU replaces the corresponding AECS semester without extending the degree",
    mobilityType: "BIP, 30-ECTS semester mobility at MTU and possible short dissertation mobility",
    actionLabel: "View the confirmed TUIASI pathway",
    officialUrl: "https://etti.tuiasi.ro/2026/09/16/ingenium-pathway-un-parcurs-international-pentru-studentii-masterului-aecs/",
    sourceId: "fc-full-tuiasi-aecs",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live", "fc-full-tuiasi-aecs"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "course-rethinking-assessment": {
    title: "Rethinking Inclusive Assessment in Higher Education",
    status: "Ongoing",
    statusOverride: undefined,
    availability: "Open to self-enrolment through the INGENIUM Course Catalogue or Education Platform",
    fullDescription: "An online, asynchronous and self-paced 8-ECTS staff-development course on inclusive assessment, Universal Design for Learning and responsible generative AI. It was developed through a University of Crete-led Education Lab project with MTU, TUIASI, Xamk, Rouen, Ud’A and Medical University Sofia.",
    universityIds: ["university-uoc", "university-mtu", "university-tuiasi", "university-xamk", "university-urn", "university-uda", "university-mus"],
    hostUniversityId: "university-uoc",
    applicationOpenDate: "2026-03-03",
    ects: 8,
    deliveryMode: "Online, asynchronous and self-paced",
    eligibility: "INGENIUM academic and teaching staff, researchers with teaching responsibilities, PhD candidates who teach, and teaching assistants",
    actionLabel: "Enrol through the official platform",
    officialUrl: "https://ingenium-university.eu/rethinking-inclusive-assessment-in-higher-education-assessment-as-learning-in-the-age-of-ai/",
    sourceId: "fc-full-inclusive-assessment",
    sourceIds: ["fc-rethinking-assessment", "fc-full-inclusive-assessment"],
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "opportunity-annual-education-call-2026": {
    status: "Open now",
    statusOverride: undefined,
    availability: "Open: fast-track final deadline 16 October; general expression of interest 13 November; general final deadline 18 December 2026. Older official fragments retain conflicting dates.",
    actionLabel: "Open the live annual call",
    confidence: "High",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "project-ingenium-ed": {
    status: "Ongoing",
    availability: "Funded 36-month European Degree exploratory action running through December 2029",
    fullDescription: "All ten partners are adapting existing joint programmes and developing CBPT, SMAC², MIDAS and the Bachelor in Innovation and Entrepreneurship against European Degree Label criteria. The project also pilots a common EGTC structure and targets support for at least 200 students, including underrepresented learners.",
    officialUrl: "https://www.tuiasi.ro/news/ingenium-ed-the-ingenium-alliance-is-preparing-the-new-generation-of-joint-european-study-programmes/?lang=en",
    sourceIds: ["fc-ingenium-ed-2026"],
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "project-next-ingenium": {
    status: "Upcoming",
    fullDescription: "The approximately €7.2 million bridge phase runs through December 2028. Published targets are seven joint programmes with enrolled students, more than 20 Pathways, 20 microcredentials, over 100 shared courses and about 3,000 mobility experiences. These are targets, not completed outcomes.",
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "platform-education": {
    fullDescription: "D3.3 documents Moodle as the shared learning platform with SAML2 authentication. The Digital Wellbeing module and first joint microcredential provide concrete delivery evidence. Public technical documentation still does not establish a complete partner-by-partner identity, security or uptime matrix.",
    sourceIds: ["digital-ingenium", "fc-full-d33", "fc-full-digital-wellbeing", "fc-full-first-microcredential"],
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "platform-open-data": {
    fullDescription: "The repository is reported as operational, with D3.4 documenting v1 and a later public D3.5 file labelled v3. The progress register calls the planned later deliverable v2, so the version discrepancy remains explicit.",
    sourceIds: ["microcredentials", "fc-full-d34", "fc-full-d35"],
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "community-sustainability-hub": {
    fullDescription: "A live student-led hub created from FutureProof work, supported by the Student Sustainability Board. Its stated goals include sharing SDG practice, enabling collaboration and developing a questionnaire and toolkit. Public board names are professional-role evidence; personal contact details are deliberately excluded.",
    sourceIds: ["sustainability-hub"],
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
  "initiative-ingenium-egtc": {
    status: "Under development",
    availability: "Registration was reported in progress in Finland; no final registration date was verified by the research cut-off",
    fullDescription: "The EGTC is intended to provide a durable legal and operational vehicle for joint staffing, funding, representation, education coordination and future European degrees. Governance reports describe registration work in Finland, but a completed legal-registration notice was not found.",
    sourceIds: ["fc29-annual-education-call", "fc-full-rouen-council", "fc-full-d101"],
    lastVerified: EXHAUSTIVE_RESEARCH_DATE,
  },
};

const universityRelationships: Relationship[] = activityEntities.flatMap((entity) => entity.universityIds.map((universityId) => ({
  id: `rel-exhaustive-${entity.id}-${universityId}`,
  source: entity.id,
  target: universityId,
  type: entity.hostUniversityId === universityId ? "hosted_by" : "involves",
  label: entity.hostUniversityId === universityId ? "Hosted or led by" : "Involves",
  explanation: `${entity.title} is linked to this partner by the cited official evidence.`,
  sourceIds: entity.sourceIds,
  dataClassification: "verified" as const,
})));

const semanticRelationships: Relationship[] = [
  { id: "rel-exhaustive-bi4e-connect", source: "project-bi4e", target: "platform-connect", type: "produced", label: "Produced", explanation: "CORDIS lists the CONNECT researcher-matching platform among BI4E outputs.", sourceIds: ["fc-full-bi4e-cordis", "fc-full-connect"], dataClassification: "verified" },
  { id: "rel-exhaustive-digital-wellbeing-platform", source: "module-digital-wellbeing-2024", target: "platform-education", type: "delivered_through", label: "Delivered through", explanation: "The shared module used the INGENIUM Moodle learning platform.", sourceIds: ["fc-full-digital-wellbeing", "fc-full-d33"], dataClassification: "verified" },
  { id: "rel-exhaustive-microcredential-platform", source: "microcredential-towards-framework-2026", target: "platform-education", type: "delivered_through", label: "Delivered through", explanation: "The first joint microcredential was delivered through the INGENIUM Education Platform.", sourceIds: ["fc-full-first-microcredential", "fc-full-d33"], dataClassification: "verified" },
  { id: "rel-exhaustive-eco-genium-founders", source: "project-eco-genium", target: "community-founders-hub", type: "shares_ecosystem", label: "Shares entrepreneurship ecosystem", explanation: "Both build cross-alliance entrepreneurship and innovation capacity, at institutional and student levels respectively.", sourceIds: ["fc-full-eco-genium", "founders-hub"], dataClassification: "verified" },
  { id: "rel-exhaustive-green-genium-hub", source: "project-green-genium", target: "community-sustainability-hub", type: "contributes_to", label: "Contributes to", explanation: "GreenGENIUM is a delivered student sustainability action within the alliance ecosystem.", sourceIds: ["fc-full-green-genium", "sustainability-hub"], dataClassification: "verified" },
  { id: "rel-exhaustive-taste-ilanet", source: "learning-resource-taste-cultures-languages", target: "initiative-ilanet-language-network", type: "delivered_through", label: "Delivered through", explanation: "The pre-mobility language resources support the alliance language-network model.", sourceIds: ["fc-full-taste-courses"], dataClassification: "verified" },
  { id: "rel-exhaustive-rouen-council-egtc", source: "event-alliance-council-rouen-2026", target: "initiative-ingenium-egtc", type: "advanced", label: "Advanced", explanation: "The Rouen meeting set first-year operational priorities for the planned EGTC.", sourceIds: ["fc-full-rouen-council"], dataClassification: "verified" },
  { id: "rel-exhaustive-d84-accelerator", source: "learning-resource-acceleration-d84", target: "initiative-accelerator", type: "documents", label: "Documents", explanation: "D8.4 is the final public report on the transnational accelerator and incubation model.", sourceIds: ["fc-full-d84"], dataClassification: "verified" },
  { id: "rel-exhaustive-d84-soft-landings", source: "learning-resource-acceleration-d84", target: "initiative-soft-landings", type: "documents", label: "Documents", explanation: "D8.4 records the development state of the Soft Landings model.", sourceIds: ["fc-full-d84"], dataClassification: "verified" },
  { id: "rel-exhaustive-d94-healthy-campus", source: "learning-resource-healthy-campus-d94", target: "initiative-healthy-campus", type: "documents", label: "Documents", explanation: "D9.4 is the core evidence resource for the Healthy Campus initiative.", sourceIds: ["fc-full-d94"], dataClassification: "verified" },
  { id: "rel-exhaustive-d101-egtc", source: "learning-resource-long-term-strategy-d101", target: "initiative-ingenium-egtc", type: "sets_roadmap_for", label: "Sets roadmap for", explanation: "D10.1 positions the EGTC as the central long-term legal and operational vehicle.", sourceIds: ["fc-full-d101"], dataClassification: "verified" },
  { id: "rel-exhaustive-d101-next", source: "learning-resource-long-term-strategy-d101", target: "project-next-ingenium", type: "guides", label: "Guides", explanation: "The long-term strategy frames the deeper integration pursued by Next INGENIUM.", sourceIds: ["fc-full-d101"], dataClassification: "verified" },
];

export const exhaustiveResearchRelationships: Relationship[] = [
  ...universityRelationships,
  ...semanticRelationships,
];
