import type { DataClassification, Entity, Relationship, Source } from "./data";

export const RESEARCH_CONTINUATION_DATE = "2026-09-29";

const allUniversityIds = [
  "university-mtu",
  "university-hka",
  "university-xamk",
  "university-hs",
  "university-uoc",
  "university-mus",
  "university-uniovi",
  "university-urn",
  "university-uda",
  "university-tuiasi",
];

export const researchContinuationSources: Source[] = [
  {
    id: "fc29-education-lab-projects",
    title: "15 Joint Education Lab projects selected from the latest call",
    kind: "Official INGENIUM results announcement",
    url: "https://ingenium-university.eu/15-joint-education-lab-projects-were-selected-from-the-latest-call/",
    publisher: "INGENIUM European University",
    published: "30 March 2026",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "The project names, leaders, partners and intended outputs were extracted from the official project register. Several embedded project-date fields were internally inconsistent, so project-specific dates are not asserted.",
  },
  {
    id: "fc29-education-lab-methodologies",
    title: "Innovative teaching and learning methodologies developed in INGENIUM",
    kind: "Official INGENIUM results article",
    url: "https://ingenium-university.eu/14-innovative-teaching-and-learning-methodologies-developed-in-ingenium-join-the-webinars-to-learn-more/",
    publisher: "INGENIUM European University",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "The headline says 14 methodologies, while the rendered article exposes 13 named entries. The discrepancy is preserved in the research report rather than silently resolved.",
  },
  {
    id: "fc29-bips-2026-2027",
    title: "INGENIUM Blended Intensive Programmes 2026/2027",
    kind: "Official INGENIUM programme catalogue",
    url: "https://ingenium-university.eu/students/ingenium-european-campus/short-term-mobility-opportunities/bips-2026-2027/",
    publisher: "INGENIUM European University",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "Used to recover two BIP records absent from the local dataset. One other health-care label appears to duplicate an existing BIP and was not imported as a new record.",
  },
  {
    id: "fc29-staff-linguistic-tandems",
    title: "INGENIUM Linguistic Tandems — Staff Edition",
    kind: "Official INGENIUM opportunity page",
    url: "https://ingenium-university.eu/ingenium-linguistic-tandems-staff-edition/",
    publisher: "INGENIUM European University",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
  },
  {
    id: "fc29-hka-short-stays",
    title: "Call for short stays at INGENIUM partner universities",
    kind: "Official HKA opportunity notice",
    url: "https://www.h-ka.de/ingenium-news/detailseite-news-ingenium/artikel/bewerbungsaufruf-fuer-kurzaufenthalte-an-ingenium-partnerhochschulen",
    publisher: "Karlsruhe University of Applied Sciences",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
  },
  {
    id: "fc29-uniovi-bip-applications",
    title: "University of Oviedo applications for five INGENIUM BIPs",
    kind: "Official University of Oviedo opportunity notice",
    url: "https://www.uniovi.es/actualidad/noticias/-/asset_publisher/Ru0cAJNPrm1m/content/id/15214217",
    publisher: "University of Oviedo",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
  },
  {
    id: "fc29-annual-education-call",
    title: "INGENIUM Annual Education Call 2026/2027",
    kind: "Official INGENIUM call",
    url: "https://ingenium-university.eu/iec-faculty/ingenium-annual-education-call-2026-2027/",
    publisher: "INGENIUM European University",
    published: "14 September 2026",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "The current announcement gives 16 October, 13 November and 18 December milestones, while older page fragments and summaries contain different dates. The current milestones are exposed with a verification warning.",
  },
  {
    id: "fc29-course-catalogue-autumn",
    title: "First online courses of the 2026/2027 academic year",
    kind: "Official INGENIUM course announcement",
    url: "https://ingenium-university.eu/expand-your-studies-with-the-ingenium-course-catalogue-apply-for-the-first-online-courses-of-2026-2027/",
    publisher: "INGENIUM European University",
    published: "11 August 2026",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "Deadlines and start dates were evaluated against the 29 September 2026 research cut-off so that expired registrations are not shown as open.",
  },
  {
    id: "fc29-pathways-live",
    title: "INGENIUM Pathway Programmes",
    kind: "Official INGENIUM programme index",
    url: "https://ingenium-university.eu/students/ingenium-european-campus/pathway-programmes/",
    publisher: "INGENIUM European University",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "The page claims 12 Pathways across five universities, but the live rendered catalogue exposed only six cards and two host filters. Partner evidence was used where available; the gap remains explicit.",
  },
  {
    id: "fc29-xamk-next-phase",
    title: "INGENIUM secures two more years of Erasmus+ funding for its next phase",
    kind: "Official Xamk news",
    url: "https://www.xamk.fi/en/ingenium-secures-two-more-years-of-erasmus-funding-for-its-next-phase/",
    publisher: "South-Eastern Finland University of Applied Sciences",
    published: "20 July 2026",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
    notes: "Confirms that the Social Services and Psychology for Sustainable Wellbeing Pathway begins in autumn 2026.",
  },
  {
    id: "fc29-uda-modern-languages",
    title: "INGENIUM Pathway for Modern Languages, Literatures and Cultures 2026/2027",
    kind: "Official Ud'A opportunity notice",
    url: "https://www.lingue.unich.it/avvisi/pathway-ingenium-laurea-magistrale-lingue-letterature-e-culture-moderne-lm-37-aa-2026-2027",
    publisher: "University G. d'Annunzio of Chieti-Pescara",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
  },
  {
    id: "fc29-uda-sustainable-habitat",
    title: "Sciences of Sustainable Habitat",
    kind: "Official Ud'A programme page",
    url: "https://www.unich.it/didattica/lauree-triennali-e-ciclo-unico/scienze-dellhabitat-sostenibile",
    publisher: "University G. d'Annunzio of Chieti-Pescara",
    verifiedAt: RESEARCH_CONTINUATION_DATE,
  },
];

type ContinuationEntityInput = Omit<Entity, "lastVerified" | "dataClassification" | "confidence"> & {
  confidence?: Entity["confidence"];
  dataClassification?: DataClassification;
};

function continuationEntity(input: ContinuationEntityInput): Entity {
  return {
    ...input,
    lastVerified: RESEARCH_CONTINUATION_DATE,
    confidence: input.confidence ?? "High",
    dataClassification: input.dataClassification ?? "verified",
    sourceIds: input.sourceIds ?? [input.sourceId],
  };
}

type EducationLabProjectInput = {
  id: string;
  slug: string;
  title: string;
  leader: string;
  universityIds: string[];
  hostUniversityId: string;
  themes: string[];
  studentSummary: string;
  outputs?: string;
};

const educationLabProjects: EducationLabProjectInput[] = [
  {
    id: "project-education-lab-idt-lab",
    slug: "immersive-design-thinking-lab",
    title: "Immersive Design Thinking Lab (iDT-Lab)",
    leader: "Elena Avram, TUIASI",
    universityIds: ["university-tuiasi", "university-mtu"],
    hostUniversityId: "university-tuiasi",
    themes: ["Design thinking", "Simulation", "Game-based learning"],
    studentSummary: "A game-based simulation project for transnational design-thinking and pedagogical innovation.",
    outputs: "Planned outputs include a toolkit, beta game, multilingual guide and scenario library.",
  },
  {
    id: "project-education-lab-idea-lab",
    slug: "idea-lab-inclusion-design-education-art",
    title: "IDEA Lab: Innovation through Inclusion, Design, Education, and Art",
    leader: "Beatriz Rayón Viña, University of Oviedo",
    universityIds: ["university-uniovi", "university-hs", "university-uda"],
    hostUniversityId: "university-uniovi",
    themes: ["Inclusion", "Design", "Arts"],
    studentSummary: "A cross-university lab using design and art to develop more inclusive educational practice.",
  },
  {
    id: "project-education-lab-assessment-narratives",
    slug: "rewriting-assessment-narratives",
    title: "Rewriting Assessment Narratives Through Research-Informed Practice",
    leader: "Cai Weaver, Xamk",
    universityIds: ["university-xamk", "university-uoc", "university-urn", "university-tuiasi", "university-mtu", "university-uda"],
    hostUniversityId: "university-xamk",
    themes: ["Assessment", "Research-informed teaching", "Open education"],
    studentSummary: "A six-university project translating research on assessment into practical guidance for European University alliances.",
    outputs: "The official project register identifies an open multilingual ebook as a planned output.",
  },
  {
    id: "project-education-lab-marchel",
    slug: "multimodal-artefacts-reflective-chemistry-learning",
    title: "Multimodal Artefacts for Reflective Chemistry Learning (MARCheL)",
    leader: "Constantinos Neochoritis, University of Crete",
    universityIds: ["university-uoc", "university-uniovi", "university-mtu"],
    hostUniversityId: "university-uoc",
    themes: ["Chemistry", "Reflective learning", "Multimodal learning"],
    studentSummary: "A chemistry-teaching project using multimodal artefacts to strengthen reflection and learning across three partners.",
  },
  {
    id: "project-education-lab-flexible-learning-spaces",
    slug: "inclusive-flexible-learning-spaces-academy",
    title: "Inclusive & Flexible Learning Spaces Academy",
    leader: "Katie Power, MTU",
    universityIds: ["university-mtu", "university-hs", "university-xamk", "university-tuiasi"],
    hostUniversityId: "university-mtu",
    themes: ["Accessibility", "Hybrid learning", "Learning spaces"],
    studentSummary: "A four-university project co-designing accessible hybrid learning environments.",
    outputs: "Planned outputs include a handbook, multilingual dictionary, 360-degree tours, video case studies and a methodology guide.",
  },
  {
    id: "project-education-lab-safe-reactor-course",
    slug: "safe-reactor-collaborative-course",
    title: "Experimental and Modelling Approaches for Designing a Safe Reactor",
    leader: "Imed ben Talouba, University of Rouen Normandy",
    universityIds: ["university-urn", "university-hka"],
    hostUniversityId: "university-urn",
    themes: ["Chemical engineering", "Modelling", "Safety"],
    studentSummary: "A collaborative chemical-engineering course connecting experimental and modelling approaches to safe reactor design.",
  },
  {
    id: "project-education-lab-activados",
    slug: "activados-active-breaks",
    title: "ActivaDos: Active Breaks in University Teaching",
    leader: "Javier Fernandez-Rio, University of Oviedo",
    universityIds: ["university-uniovi", "university-urn", "university-xamk", "university-hka", "university-tuiasi", "university-mus", "university-mtu"],
    hostUniversityId: "university-uniovi",
    themes: ["Wellbeing", "Teaching practice", "Active learning"],
    studentSummary: "A seven-university project testing active breaks as a way to improve student and faculty satisfaction.",
  },
  {
    id: "project-education-lab-community-arts",
    slug: "community-intervention-through-arts",
    title: "Educational and Social Laboratory for Community Intervention through the Arts",
    leader: "José Antonio Labra Pérez, University of Oviedo",
    universityIds: ["university-uniovi", "university-hs", "university-uda"],
    hostUniversityId: "university-uniovi",
    themes: ["Community", "Arts", "Social innovation"],
    studentSummary: "A cross-university project exploring education and social intervention through the arts.",
  },
  {
    id: "project-education-lab-up2learn",
    slug: "up2learn-green-chemistry",
    title: "From UP2Green to UP2Learn: A Green Chemistry Learning Lab",
    leader: "Lucia Tonucci, Ud'A",
    universityIds: ["university-uda", "university-urn", "university-tuiasi"],
    hostUniversityId: "university-uda",
    themes: ["Green chemistry", "Sustainability", "Research-based education"],
    studentSummary: "A research-based green-chemistry learning lab connecting Ud'A, Rouen and TUIASI.",
  },
  {
    id: "project-education-lab-living-landscape",
    slug: "living-landscape-lab",
    title: "Living Landscape Lab",
    leader: "Margarita Fernández Mier, University of Oviedo",
    universityIds: ["university-uniovi", "university-hs"],
    hostUniversityId: "university-uniovi",
    themes: ["Landscape", "Sustainability", "Place-based learning"],
    studentSummary: "A University of Oviedo and Skövde collaboration using living landscapes as a context for learning.",
  },
  {
    id: "project-education-lab-team-ai",
    slug: "team-ai",
    title: "TEAM-AI",
    leader: "Martin Klepal, MTU",
    universityIds: ["university-mtu", "university-tuiasi", "university-uniovi", "university-xamk"],
    hostUniversityId: "university-mtu",
    themes: ["Artificial intelligence", "Team learning", "Teaching innovation"],
    studentSummary: "A four-university Education Lab project led by MTU focused on collaborative learning around artificial intelligence.",
  },
  {
    id: "project-education-lab-virtual-chemical-engineering-hall",
    slug: "virtual-chemical-engineering-teaching-hall",
    title: "Virtual Chemical Engineering Teaching Hall",
    leader: "Nicolas Brodu, University of Rouen Normandy",
    universityIds: ["university-urn", "university-hka"],
    hostUniversityId: "university-urn",
    themes: ["Chemical engineering", "Immersive learning", "Virtualisation"],
    studentSummary: "A project virtualising an existing chemical-engineering teaching hall for immersive practical training.",
  },
  {
    id: "project-education-lab-uni-co",
    slug: "uni-co-low-carbon-collaboration",
    title: "UNI-CO: A Low-Carbon Model for Cross-Campus Collaboration",
    leader: "Rosie Dempsey, MTU",
    universityIds: ["university-mtu", "university-tuiasi"],
    hostUniversityId: "university-mtu",
    themes: ["Low-carbon collaboration", "Student-centred learning", "Sustainability"],
    studentSummary: "An MTU-TUIASI project developing a lower-carbon model for student-centred collaboration across campuses.",
  },
  {
    id: "project-education-lab-work-integrated-learning",
    slug: "work-integrated-learning-collaborative-inquiry",
    title: "Enhancing Work-Integrated Learning through Collaborative Inquiry",
    leader: "Tom O'Mahony, MTU",
    universityIds: ["university-mtu", "university-uniovi", "university-hka"],
    hostUniversityId: "university-mtu",
    themes: ["Work-integrated learning", "Action research", "Micro-credentials"],
    studentSummary: "A cross-European action-research project developing a micro-credential around work-integrated learning.",
  },
  {
    id: "project-education-lab-literacy-toolkit",
    slug: "school-out-of-school-literacy-toolkit",
    title: "Bridging In-School and Out-Of-School Literacy Practices",
    leader: "Vasia Tsami, University of Crete",
    universityIds: ["university-uoc", "university-uniovi"],
    hostUniversityId: "university-uoc",
    themes: ["Literacy", "Teacher education", "Online learning"],
    studentSummary: "A University of Crete and Oviedo project developing an online toolkit that bridges formal and informal literacy practices.",
  },
];

const educationLabEntities: Entity[] = educationLabProjects.map((project) => continuationEntity({
  id: project.id,
  slug: project.slug,
  title: project.title,
  type: "project",
  subtype: "Selected INGENIUM Education Lab project",
  studentSummary: project.studentSummary,
  fullDescription: `${project.leader} leads this selected Education Lab project.${project.outputs ? ` ${project.outputs}` : ""}`,
  status: "Ongoing",
  availability: "Selected in the latest published Education Lab call; project-specific delivery dates are not consistently published",
  universityIds: project.universityIds,
  hostUniversityId: project.hostUniversityId,
  themes: project.themes,
  workPackage: "WP5",
  actionLabel: "View selected project",
  officialUrl: "https://ingenium-university.eu/15-joint-education-lab-projects-were-selected-from-the-latest-call/",
  sourceId: "fc29-education-lab-projects",
  sourceIds: ["fc29-education-lab-projects", "fc29-education-lab-methodologies"],
}));

const opportunityAndBipEntities: Entity[] = [
  continuationEntity({
    id: "bip-study-skills-2026",
    slug: "study-skills-2026",
    title: "Study Skills",
    type: "bip",
    subtype: "Blended Intensive Programme",
    studentSummary: "A Xamk-hosted BIP in Mikkeli focused on the practical study skills students need for successful higher education.",
    fullDescription: "The official 2026/2027 BIP catalogue lists this as a 3 ECTS programme for 25 students in September 2026. The catalogue does not expose enough exact schedule information to state whether delivery is complete at the research cut-off.",
    status: "Verification required",
    statusOverride: "Verification required",
    availability: "Listed for September 2026; exact delivery and completion dates require confirmation",
    universityIds: ["university-xamk"],
    hostUniversityId: "university-xamk",
    countries: ["Finland"],
    city: "Mikkeli",
    themes: ["Study skills", "Student success", "International learning"],
    academicLevel: "Higher education students",
    deliveryMode: "Blended",
    mobilityType: "Short-term physical mobility plus virtual learning",
    dateLabel: "September 2026 — exact dates not published",
    ects: 3,
    language: "English",
    capacity: "25 students",
    eligibility: "Students at INGENIUM partner universities; local nomination conditions apply",
    actionLabel: "Verify current programme status",
    officialUrl: "https://ingenium-university.eu/students/ingenium-european-campus/short-term-mobility-opportunities/bips-2026-2027/",
    sourceId: "fc29-bips-2026-2027",
    confidence: "High",
  }),
  continuationEntity({
    id: "bip-ingenium-inclusion-2027",
    slug: "ingenium-inclusion-bip-2027",
    title: "INGENIUM Inclusion BIP",
    type: "bip",
    subtype: "Blended Intensive Programme",
    studentSummary: "A transversal inclusion and equality BIP planned by the University of Rouen Normandy for March 2027.",
    fullDescription: "The official alliance material identifies a 3 ECTS Inclusion BIP coordinated by Rouen, with March 2027 marked as provisional. Students should wait for exact dates and their home-university nomination route.",
    status: "Upcoming",
    availability: "Planned for March 2027; exact dates are still to be confirmed",
    universityIds: ["university-urn"],
    hostUniversityId: "university-urn",
    countries: ["France"],
    city: "Rouen",
    themes: ["Inclusion", "Equality", "Diversity"],
    academicLevel: "Higher education students",
    deliveryMode: "Blended",
    mobilityType: "Short-term physical mobility plus virtual learning",
    dateLabel: "March 2027 — to be confirmed",
    ects: 3,
    language: "English",
    eligibility: "Students at INGENIUM partner universities; local nomination conditions apply",
    actionLabel: "Follow official BIP updates",
    officialUrl: "https://ingenium-university.eu/students/ingenium-european-campus/short-term-mobility-opportunities/bips-2026-2027/",
    sourceId: "fc29-bips-2026-2027",
    confidence: "High",
  }),
  continuationEntity({
    id: "opportunity-staff-linguistic-tandems-2026",
    slug: "staff-linguistic-tandems-2026",
    title: "INGENIUM Linguistic Tandems — Staff Edition",
    type: "opportunity",
    subtype: "Alliance language-exchange opportunity",
    studentSummary: "A six-to-eight-week peer language exchange for teaching, administrative and professional staff across the alliance.",
    fullDescription: "Participants are matched in pairs for informal language practice. It is not a class: there is no teacher, exam or fixed curriculum.",
    status: "Open",
    availability: "Applications open until 2 October 2026",
    universityIds: allUniversityIds,
    themes: ["Languages", "Staff mobility", "Intercultural learning"],
    deliveryMode: "Peer exchange",
    applicationDeadline: "2026-10-02",
    dateLabel: "Six to eight weeks after matching",
    eligibility: "Teaching, administrative and professional staff at the ten INGENIUM universities",
    actionLabel: "Apply for a tandem",
    officialUrl: "https://ingenium-university.eu/ingenium-linguistic-tandems-staff-edition/",
    sourceId: "fc29-staff-linguistic-tandems",
    featured: true,
  }),
  continuationEntity({
    id: "opportunity-hka-ingenium-short-stays-2026",
    slug: "hka-ingenium-short-stays-2026",
    title: "HKA Short Stays at INGENIUM Partner Universities",
    type: "opportunity",
    subtype: "Staff collaboration and teaching mobility",
    studentSummary: "An HKA call supporting short visits to INGENIUM partners to begin or sustain COIL and teaching-tandem collaboration.",
    fullDescription: "The official HKA notice says applications are handled on a first-come, first-served basis and submitted using the linked form by email.",
    status: "Open",
    availability: "Applications open until 25 October 2026; first come, first served",
    universityIds: ["university-hka"],
    hostUniversityId: "university-hka",
    countries: ["Germany"],
    themes: ["Staff mobility", "COIL", "Teaching collaboration"],
    mobilityType: "Short staff visit to an INGENIUM partner",
    applicationDeadline: "2026-10-25",
    eligibility: "HKA staff seeking to establish or sustain COIL or teaching-tandem cooperation with an INGENIUM partner",
    actionLabel: "View HKA application details",
    officialUrl: "https://www.h-ka.de/ingenium-news/detailseite-news-ingenium/artikel/bewerbungsaufruf-fuer-kurzaufenthalte-an-ingenium-partnerhochschulen",
    sourceId: "fc29-hka-short-stays",
    featured: true,
  }),
  continuationEntity({
    id: "opportunity-uniovi-bip-window-november-2026",
    slug: "uniovi-bip-applications-november-2026",
    title: "University of Oviedo BIP Applications — November 2026 Window",
    type: "opportunity",
    subtype: "Local BIP application route",
    studentSummary: "A University of Oviedo application window for the International Project Challenge and MedChem BIPs taking place in 2027.",
    fullDescription: "The official UniOvi notice gives a 2–15 November 2026 local application period. Applicants need B2 English and apply through the SIES route; selection is competitive.",
    status: "Opens soon",
    availability: "Applications open 2–15 November 2026",
    universityIds: ["university-uniovi"],
    hostUniversityId: "university-uniovi",
    countries: ["Spain"],
    themes: ["BIP", "Short-term mobility", "Student applications"],
    academicLevel: "Bachelor, Master and Doctoral students",
    applicationOpenDate: "2026-11-02",
    applicationDeadline: "2026-11-15",
    eligibility: "University of Oviedo Bachelor, Master or Doctoral students with B2 English, subject to the official competitive selection procedure",
    funding: "Erasmus+ mobility funding under the local call conditions",
    actionLabel: "Prepare the UniOvi application",
    officialUrl: "https://www.uniovi.es/actualidad/noticias/-/asset_publisher/Ru0cAJNPrm1m/content/id/15214217",
    sourceId: "fc29-uniovi-bip-applications",
    featured: true,
  }),
];

export const researchContinuationEntities: Entity[] = [
  ...educationLabEntities,
  ...opportunityAndBipEntities,
];

export const researchContinuationOverrides: Partial<Record<string, Partial<Entity>>> = {
  "course-sustainable-wellbeing": {
    status: "Coming soon",
    availability: "Application closed 27 September 2026; teaching begins 12 October 2026",
    actionLabel: "View course details",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["autumn-learning-2026", "course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "course-beginners-finnish-1": {
    status: "Ongoing",
    availability: "Application closed; course began 14 September 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["autumn-learning-2026", "course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "course-beginners-finnish-2": {
    status: "Ongoing",
    availability: "Application closed; course began 14 September 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["autumn-learning-2026", "course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "course-culture-finland": {
    status: "Ongoing",
    availability: "Application closed; course began 14 September 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["autumn-learning-2026", "course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "module-acute-care-professional-development": {
    status: "Ongoing",
    availability: "Application closed; module began 16 September 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["autumn-learning-2026", "course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "module-acute-care-research-development": {
    status: "Coming soon",
    availability: "Application closed; module begins 16 November 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["autumn-learning-2026", "course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "course-innovation-management-entrepreneurship": {
    status: "Ongoing",
    statusOverride: undefined,
    availability: "Course began 29 September 2026; the published application deadline has passed",
    fullDescription: "A free ten-week virtual course developed by MTU, the University of Crete and the University of Oviedo, with weekly live sessions and a digital badge. The standard SSO route covers eight partners; MTU and HKA use an expression-of-interest route.",
    workload: "Ten weeks with weekly live sessions",
    funding: "Free to eligible INGENIUM participants",
    actionLabel: "View course details",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["course-catalogue-2026", "fc29-course-catalogue-autumn"],
  },
  "opportunity-annual-education-call-2026": {
    status: "Verification required",
    statusOverride: "Verification required",
    availability: "Open: fast-track final deadline 16 October; general expression of interest 13 November; general final deadline 18 December 2026. Older official page fragments conflict.",
    fullDescription: "The current announcement covers nine categories: joint programmes; Pathways and windows; doctoral collaboration; BIPs; microcredentials and micromodules; collaborative teaching; teaching innovation; Staff Academy training; and Course Catalogue contributions. Academic staff and programme directors can lead, while technical staff, students and external stakeholders can co-create. Older official summaries contain different deadlines, so the record remains verification required.",
    applicationDeadline: "2026-12-18",
    eligibility: "Academic staff and programme directors across all ten partners may lead; technical staff, students and external stakeholders may co-create",
    actionLabel: "Open the current call and verify route",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-annual-education-call",
    sourceIds: ["education-call-2026", "fc29-annual-education-call"],
  },
  "programme-cbpt": {
    status: "Coming soon",
    availability: "Applications closed 6 September 2026; the first cohort is due to begin 1 October 2026",
    actionLabel: "View programme details",
    lastVerified: RESEARCH_CONTINUATION_DATE,
  },
  "framework-pathways": {
    status: "Verification required",
    statusOverride: "Verification required",
    availability: "The official page claims 12 Pathways across five universities, but its live catalogue currently renders only six programmes across two hosts. Partner pages confirm additional routes; the full live register remains incomplete.",
    studentSummary: "The Pathway model is active, but the current public register is incomplete and should not be treated as a definitive list of all 12 routes.",
    actionLabel: "View the partial official register",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live", "fc29-xamk-next-phase", "fc29-uda-modern-languages", "fc29-uda-sustainable-habitat"],
  },
  "pathway-commerce-marketing": {
    status: "Ongoing",
    availability: "Listed in the live Pathway catalogue",
    city: "Gijón",
    language: "Spanish and English",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "High",
  },
  "pathway-social-work": {
    status: "Ongoing",
    availability: "Listed in the live Pathway catalogue",
    city: "Gijón",
    language: "Spanish",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "High",
  },
  "pathway-tourism": {
    status: "Ongoing",
    availability: "Listed in the live Pathway catalogue",
    city: "Gijón",
    language: "Spanish and English",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "High",
  },
  "pathway-biotechnology-environment-health": {
    status: "Ongoing",
    availability: "Listed in the live Pathway catalogue",
    city: "Oviedo",
    language: "English",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "High",
  },
  "pathway-electrical-energy": {
    status: "Ongoing",
    availability: "Listed in the live Pathway catalogue",
    city: "Gijón",
    language: "English",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "High",
  },
  "pathway-telecommunications-it": {
    status: "Ongoing",
    availability: "Listed in the live Pathway catalogue",
    city: "Iași",
    language: "English",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "High",
  },
  "pathway-social-services": {
    status: "Ongoing",
    availability: "Xamk confirms the Social Services and Psychology for Sustainable Wellbeing Pathway begins in autumn 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-xamk-next-phase",
    sourceIds: ["pathway-framework-live", "fc29-xamk-next-phase"],
    confidence: "High",
  },
  "pathway-sustainable-habitat": {
    status: "Ongoing",
    availability: "The Ud'A degree page identifies the programme as an INGENIUM Pathway route",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-uda-sustainable-habitat",
    sourceIds: ["pathway-framework-live", "fc29-uda-sustainable-habitat"],
    confidence: "High",
  },
  "pathway-modern-languages-management": {
    status: "Coming soon",
    availability: "The 2026/2027 route begins 1 October 2026; the local selection window has closed",
    startDate: "2026-10-01",
    capacity: "Five places in the published local selection",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-uda-modern-languages",
    sourceIds: ["pathway-framework-live", "fc29-uda-modern-languages"],
    confidence: "High",
  },
  "pathway-automotive-electronics": {
    status: "Verification required",
    statusOverride: "Verification required",
    availability: "The central index exposes the TUIASI programme label, but its linked detail route is broken or mismatched",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceId: "fc29-pathways-live",
    sourceIds: ["pathway-framework-live", "fc29-pathways-live"],
    confidence: "Medium",
  },
  "bip-sustainable-cosmetics": {
    availability: "The published University of Oviedo application window closed 21 July 2026; physical delivery is scheduled for 5–9 October 2026",
    dateLabel: "5–9 October 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["bips-2627", "fc29-uniovi-bip-applications"],
  },
  "bip-corporate-responsibility": {
    availability: "The published University of Oviedo application window closed 15 September 2026; physical delivery is scheduled for 30 November–4 December 2026",
    dateLabel: "30 November–4 December 2026",
    lastVerified: RESEARCH_CONTINUATION_DATE,
    sourceIds: ["bips-2627", "fc29-uniovi-bip-applications"],
  },
};

const universityRelationship = (entity: Entity, universityId: string): Relationship => ({
  id: `rel-continuation-${entity.id}-${universityId}`,
  source: entity.id,
  target: universityId,
  type: entity.hostUniversityId === universityId ? "hosted_by" : "involves",
  label: entity.hostUniversityId === universityId ? "Hosted or led by" : "Involves",
  explanation: `${entity.title} is linked to this INGENIUM partner by the cited official source.`,
  sourceIds: entity.sourceIds,
  dataClassification: "verified",
});

const educationLabRelationships: Relationship[] = educationLabEntities.map((entity) => ({
  id: `rel-continuation-${entity.id}-education-lab`,
  source: entity.id,
  target: "initiative-education-lab",
  type: "part_of",
  label: "Part of",
  explanation: `${entity.title} was selected through the latest published INGENIUM Education Lab call.`,
  sourceIds: ["fc29-education-lab-projects"],
  dataClassification: "verified",
}));

const extraRelationships: Relationship[] = [
  {
    id: "rel-continuation-staff-tandems-ilanet",
    source: "opportunity-staff-linguistic-tandems-2026",
    target: "initiative-ilanet-language-network",
    type: "delivered_through",
    label: "Delivered through",
    explanation: "The staff tandem is an operational language-exchange route connected to the alliance language-network model.",
    sourceIds: ["fc29-staff-linguistic-tandems"],
    dataClassification: "verified",
  },
  {
    id: "rel-continuation-hka-short-stays-staff-academy",
    source: "opportunity-hka-ingenium-short-stays-2026",
    target: "initiative-staff-academy",
    type: "supports",
    label: "Supports",
    explanation: "The HKA mobility call supports cross-partner teaching collaboration and COIL development.",
    sourceIds: ["fc29-hka-short-stays"],
    dataClassification: "verified",
  },
  {
    id: "rel-continuation-uniovi-window-ipc",
    source: "opportunity-uniovi-bip-window-november-2026",
    target: "bip-international-project-challenge",
    type: "application_for",
    label: "Application for",
    explanation: "The 2–15 November UniOvi window includes the April 2027 International Project Challenge BIP.",
    sourceIds: ["fc29-uniovi-bip-applications"],
    dataClassification: "verified",
  },
  {
    id: "rel-continuation-uniovi-window-medchem",
    source: "opportunity-uniovi-bip-window-november-2026",
    target: "bip-medchem",
    type: "application_for",
    label: "Application for",
    explanation: "The 2–15 November UniOvi window includes the June 2027 MedChem BIP.",
    sourceIds: ["fc29-uniovi-bip-applications"],
    dataClassification: "verified",
  },
  {
    id: "rel-continuation-study-skills-platform",
    source: "bip-study-skills-2026",
    target: "platform-education",
    type: "listed_on",
    label: "Listed on",
    explanation: "The Study Skills BIP is listed in the official 2026/2027 alliance catalogue.",
    sourceIds: ["fc29-bips-2026-2027"],
    dataClassification: "verified",
  },
  {
    id: "rel-continuation-inclusion-bip-platform",
    source: "bip-ingenium-inclusion-2027",
    target: "platform-education",
    type: "listed_on",
    label: "Listed on",
    explanation: "The Inclusion BIP is listed in the official 2026/2027 alliance materials.",
    sourceIds: ["fc29-bips-2026-2027"],
    dataClassification: "verified",
  },
];

export const researchContinuationRelationships: Relationship[] = [
  ...researchContinuationEntities.flatMap((entity) => entity.universityIds.map((universityId) => universityRelationship(entity, universityId))),
  ...educationLabRelationships,
  ...extraRelationships,
];
