import type { Entity, Source } from "./data";

export const CATALOGUE_RESEARCH_DATE = "2026-10-01";

export const catalogueResearchSources: Source[] = [
  {
    id: "fc-cat-from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-ba",
    title: "From UP2Green to UP2Learn: A Green Chemistry Learning Lab for Research-Based Education",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-based-education/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-evidence-based-practice-and-implementation-in-acute-care-nursing",
    title: "Evidence-based practice and implementation in acute care nursing",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/evidence-based-practice-and-implementation-in-acute-care-nursing-2/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-using-wellbeing-skills-to-promote-studying-ability",
    title: "Using Wellbeing Skills to Promote Studying Ability",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/using-wellbeing-skills-to-promote-studying-ability/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-health-promotion-strategies-for-health-professionals",
    title: "Health Promotion Strategies for Health Professionals",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/health-promotion-strategies-for-health-professionals-2/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-micro-credential-learning-design",
    title: "Micro-credential learning design",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/micro-credential-learning-design/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-education-for-sustainable-development-esd-for-university-staff",
    title: "Education for Sustainable Development (ESD) for University Staff",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/education-for-sustainable-development-esd-for-university-staff/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-digital-accessibility",
    title: "Digital Accessibility",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/digital-accessibility/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-gender-scape-a-serious-game-about-gender-equality",
    title: "GendEr SCAPE – A Serious Game about Gender Equality",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/gender-scape-a-serious-game-about-gender-equality/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-science-meets-industry-driving-innovation-through-industry-challenges",
    title: "Science Meets Industry – Driving Innovation Through Industry Challenges",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/science-meets-industry-driving-innovation-through-industry-challenges/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-science-meets-industry-ethical-ai-development",
    title: "Science Meets Industry – Ethical AI Development",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/science-meets-industry-ethical-ai-development/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-science-meets-industry-creative-convergence-innovating-industries-togeth",
    title: "Science Meets Industry – Creative Convergence: Innovating Industries Together",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/science-meets-industry-creative-convergence-innovating-industries-together/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-intercultural-team-based-learning",
    title: "Intercultural Team Based Learning",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/intercultural-team-based-learning/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by",
    title: "Crystallization kinetics and mechanical properties of PHB plasticized by commercial and cardanol derivatives",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by-commercial-and-cardanol-derivatives/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-coil-collaboration-to-promote-technical-language-and-intercultural-compe",
    title: "COIL Collaboration to Promote Technical Language and Intercultural Competence: Technical English C1 & English across the Disciplines",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/coil-collaboration-to-promote-technical-language-and-intercultural-competence-technical-english-c1-english-across-the-disciplines/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-international-communication",
    title: "International Communication",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/international-communication/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-how-to-become-a-disability-ambassador",
    title: "How to become a disability ambassador",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/how-to-become-a-disability-ambassador/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-introduction-to-polymer-characterization",
    title: "Introduction to polymer characterization",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/introduction-to-polymer-characterization/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-differential-holistic-and-integrative-approach-to-patient-care",
    title: "Differential, holistic and integrative approach to patient care",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/differential-holistic-and-integrative-approach-to-patient-care/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
  {
    id: "fc-cat-sustainability-course-materials-for-teaching",
    title: "Sustainability course materials for teaching",
    kind: "Official INGENIUM course detail page",
    url: "https://ingenium-university.eu/courses/sustainability-course-material-for-teaching/",
    publisher: "INGENIUM European University",
    verifiedAt: CATALOGUE_RESEARCH_DATE,
    notes: "Title and public detail page verified. Missing schedule, ECTS, host or access fields are deliberately not inferred.",
  },
];

export const catalogueResearchEntities: Entity[] = [
  {
    id: "microcredential-from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-ba",
    slug: "from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-ba",
    title: "From UP2Green to UP2Learn: A Green Chemistry Learning Lab for Research-Based Education",
    type: "microcredential",
    subtype: "Green-chemistry microcredential",
    studentSummary: "this INGENIUM micro-credential that provides advanced training in green chemistry and sustainable chemical processes, focusing on the valorization of waste streams (e.g., CO₂, lignin, glycerol) through catalytic and materials-based approaches. Building on the research outcomes of the INGENIUM pro...",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Sustainability","Teaching and learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-based-education/",
    sourceId: "fc-cat-from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-ba",
    sourceIds: ["fc-cat-from-up2green-to-up2learn-a-green-chemistry-learning-lab-for-research-ba", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-evidence-based-practice-and-implementation-in-acute-care-nursing",
    slug: "evidence-based-practice-and-implementation-in-acute-care-nursing",
    title: "Evidence-based practice and implementation in acute care nursing",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Evidence-based practice and implementation in acute care nursing. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Health","Professional learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/evidence-based-practice-and-implementation-in-acute-care-nursing-2/",
    sourceId: "fc-cat-evidence-based-practice-and-implementation-in-acute-care-nursing",
    sourceIds: ["fc-cat-evidence-based-practice-and-implementation-in-acute-care-nursing", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-using-wellbeing-skills-to-promote-studying-ability",
    slug: "using-wellbeing-skills-to-promote-studying-ability",
    title: "Using Wellbeing Skills to Promote Studying Ability",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "The aim of this course is to promote students' study ability and wellbeing. The course offers tools to support learning, coping and wellbeing. In this course, students study strongly themselves, reflecting on their own learning and well-being. The course contains learning material in many differe...",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Wellbeing","Study skills"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/using-wellbeing-skills-to-promote-studying-ability/",
    sourceId: "fc-cat-using-wellbeing-skills-to-promote-studying-ability",
    sourceIds: ["fc-cat-using-wellbeing-skills-to-promote-studying-ability", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-health-promotion-strategies-for-health-professionals",
    slug: "health-promotion-strategies-for-health-professionals",
    title: "Health Promotion Strategies for Health Professionals",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An on-site intensive course for health-science professionals on the design and planning of health-promotion strategies.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Health","Professional learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/health-promotion-strategies-for-health-professionals-2/",
    sourceId: "fc-cat-health-promotion-strategies-for-health-professionals",
    sourceIds: ["fc-cat-health-promotion-strategies-for-health-professionals", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "microcredential-micro-credential-learning-design",
    slug: "micro-credential-learning-design",
    title: "Micro-credential learning design",
    type: "microcredential",
    subtype: "Staff microcredential-design course",
    studentSummary: "A self-paced, self-study course on the basics of micro-credential learning design.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Education","Professional learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/micro-credential-learning-design/",
    sourceId: "fc-cat-micro-credential-learning-design",
    sourceIds: ["fc-cat-micro-credential-learning-design", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-education-for-sustainable-development-esd-for-university-staff",
    slug: "education-for-sustainable-development-esd-for-university-staff",
    title: "Education for Sustainable Development (ESD) for University Staff",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Education for Sustainable Development (ESD) for University Staff. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Sustainability","Teaching and learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/education-for-sustainable-development-esd-for-university-staff/",
    sourceId: "fc-cat-education-for-sustainable-development-esd-for-university-staff",
    sourceIds: ["fc-cat-education-for-sustainable-development-esd-for-university-staff", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-digital-accessibility",
    slug: "digital-accessibility",
    title: "Digital Accessibility",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Digital Accessibility. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Inclusion","Accessibility"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/digital-accessibility/",
    sourceId: "fc-cat-digital-accessibility",
    sourceIds: ["fc-cat-digital-accessibility", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-gender-scape-a-serious-game-about-gender-equality",
    slug: "gender-scape-a-serious-game-about-gender-equality",
    title: "GendEr SCAPE – A Serious Game about Gender Equality",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "Students",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Inclusion","Accessibility"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/gender-scape-a-serious-game-about-gender-equality/",
    sourceId: "fc-cat-gender-scape-a-serious-game-about-gender-equality",
    sourceIds: ["fc-cat-gender-scape-a-serious-game-about-gender-equality", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-science-meets-industry-driving-innovation-through-industry-challenges",
    slug: "science-meets-industry-driving-innovation-through-industry-challenges",
    title: "Science Meets Industry – Driving Innovation Through Industry Challenges",
    type: "course",
    subtype: "Science Meets Industry course",
    studentSummary: "This BIP brings together academia and industry by tasking interdisciplinary MSc and PhD student groups with addressing concrete challenges provided by industrial partners, from different domains, e.g., smart cities and mobility, digitalization and AI, etc, that can drive innovation forward.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Education","Professional learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/science-meets-industry-driving-innovation-through-industry-challenges/",
    sourceId: "fc-cat-science-meets-industry-driving-innovation-through-industry-challenges",
    sourceIds: ["fc-cat-science-meets-industry-driving-innovation-through-industry-challenges", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-science-meets-industry-ethical-ai-development",
    slug: "science-meets-industry-ethical-ai-development",
    title: "Science Meets Industry – Ethical AI Development",
    type: "course",
    subtype: "Science Meets Industry course",
    studentSummary: "Artificial Intelligence (AI) is transforming industries and research fields across Europe and globally. Ensuring the ethical development and deployment of AI systems is critical to safeguard human rights, fairness, and societal well-being. This program addresses a pressing need for interdisciplin...",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Artificial intelligence","Industry"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/science-meets-industry-ethical-ai-development/",
    sourceId: "fc-cat-science-meets-industry-ethical-ai-development",
    sourceIds: ["fc-cat-science-meets-industry-ethical-ai-development", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-science-meets-industry-creative-convergence-innovating-industries-togeth",
    slug: "science-meets-industry-creative-convergence-innovating-industries-togeth",
    title: "Science Meets Industry – Creative Convergence: Innovating Industries Together",
    type: "course",
    subtype: "Science Meets Industry course",
    studentSummary: "By forging connections between diverse fields, this initiative exemplifies the synergy that arises when creativity meets collaboration. Students will engage in a dynamic process of innovation, journeying through three pivotal pillars of the 5Cos framework: co-ideation, co-valuation, and co-design...",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Education","Professional learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/science-meets-industry-creative-convergence-innovating-industries-together/",
    sourceId: "fc-cat-science-meets-industry-creative-convergence-innovating-industries-togeth",
    sourceIds: ["fc-cat-science-meets-industry-creative-convergence-innovating-industries-togeth", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-intercultural-team-based-learning",
    slug: "intercultural-team-based-learning",
    title: "Intercultural Team Based Learning",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Intercultural Team Based Learning. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Communication","Intercultural learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/intercultural-team-based-learning/",
    sourceId: "fc-cat-intercultural-team-based-learning",
    sourceIds: ["fc-cat-intercultural-team-based-learning", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by",
    slug: "crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by",
    title: "Crystallization kinetics and mechanical properties of PHB plasticized by commercial and cardanol derivatives",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Crystallization kinetics and mechanical properties of PHB plasticized by commercial and cardanol derivatives. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Chemistry","Materials science"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by-commercial-and-cardanol-derivatives/",
    sourceId: "fc-cat-crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by",
    sourceIds: ["fc-cat-crystallization-kinetics-and-mechanical-properties-of-phb-plasticized-by", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-coil-collaboration-to-promote-technical-language-and-intercultural-compe",
    slug: "coil-collaboration-to-promote-technical-language-and-intercultural-compe",
    title: "COIL Collaboration to Promote Technical Language and Intercultural Competence: Technical English C1 & English across the Disciplines",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for COIL Collaboration to Promote Technical Language and Intercultural Competence: Technical English C1 & English across the Disciplines. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Communication","Intercultural learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/coil-collaboration-to-promote-technical-language-and-intercultural-competence-technical-english-c1-english-across-the-disciplines/",
    sourceId: "fc-cat-coil-collaboration-to-promote-technical-language-and-intercultural-compe",
    sourceIds: ["fc-cat-coil-collaboration-to-promote-technical-language-and-intercultural-compe", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-international-communication",
    slug: "international-communication",
    title: "International Communication",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for International Communication. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Communication","Intercultural learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/international-communication/",
    sourceId: "fc-cat-international-communication",
    sourceIds: ["fc-cat-international-communication", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-how-to-become-a-disability-ambassador",
    slug: "how-to-become-a-disability-ambassador",
    title: "How to become a disability ambassador",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for How to become a disability ambassador. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Inclusion","Accessibility"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/how-to-become-a-disability-ambassador/",
    sourceId: "fc-cat-how-to-become-a-disability-ambassador",
    sourceIds: ["fc-cat-how-to-become-a-disability-ambassador", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-introduction-to-polymer-characterization",
    slug: "introduction-to-polymer-characterization",
    title: "Introduction to polymer characterization",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Introduction to polymer characterization. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Chemistry","Materials science"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/introduction-to-polymer-characterization/",
    sourceId: "fc-cat-introduction-to-polymer-characterization",
    sourceIds: ["fc-cat-introduction-to-polymer-characterization", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "course-differential-holistic-and-integrative-approach-to-patient-care",
    slug: "differential-holistic-and-integrative-approach-to-patient-care",
    title: "Differential, holistic and integrative approach to patient care",
    type: "course",
    subtype: "INGENIUM catalogue course",
    studentSummary: "An official INGENIUM catalogue listing for Differential, holistic and integrative approach to patient care. The public page does not consistently expose schedule, ECTS, host or live-enrolment fields.",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Health","Professional learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/differential-holistic-and-integrative-approach-to-patient-care/",
    sourceId: "fc-cat-differential-holistic-and-integrative-approach-to-patient-care",
    sourceIds: ["fc-cat-differential-holistic-and-integrative-approach-to-patient-care", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
  {
    id: "learning_resource-sustainability-course-materials-for-teaching",
    slug: "sustainability-course-materials-for-teaching",
    title: "Sustainability course materials for teaching",
    type: "learning_resource",
    subtype: "Open teaching-material collection",
    studentSummary: "These are flexible to use course materials, so this is no course. No registration needed - This material is for teaching, so use enrollment to access the material. The target-group is teachers who will integrate these materials in their programs and courses for students. The materials can also be...",
    fullDescription: "This record preserves a distinct item from the 40-entry public INGENIUM course-catalogue snapshot. Where the official detail page does not publish structured dates, ECTS, host, workload or enrolment state, those fields remain unset rather than inferred.",
    status: "Access unverified",
    availability: "Public catalogue detail page; current enrolment and delivery dates require confirmation",
    universityIds: [],
    themes: ["Sustainability","Teaching and learning"],
    actionLabel: "Open the official course page",
    officialUrl: "https://ingenium-university.eu/courses/sustainability-course-material-for-teaching/",
    sourceId: "fc-cat-sustainability-course-materials-for-teaching",
    sourceIds: ["fc-cat-sustainability-course-materials-for-teaching", "course-catalogue-2026"],
    lastVerified: CATALOGUE_RESEARCH_DATE,
    confidence: "Medium",
    dataClassification: "verified",
  },
];

